- boulderD9_base.libraries.yml
- css/ucb-article-list.css
- css/ucb-article.css
- js/ucb-article-list.js
- templates/content/node--ucb-article-list.html.twig
- templates/content/node--ucb-article.html.twig
- templates/paragraphs/paragraph--article-content.html.twig
> Adding in template stubs for Article and Article List

- boulderD9_base.libraries.yml
- css/ucb-how-to-page.css
- templates/content/node--how-to-page.html.twig
- templates/field/field--field_how_to_estimated_costs.html.twig
- templates/field/field--field_how_to_step_image.html.twig
- templates/field/field--field_how_to_step_title.html.twig
- templates/field/field--field_how_to_tools.html.twig
- templates/paragraphs/paragraph--how-to-individual-step.html.twig
> implemented howto

- css/ucb-article.css
Resolves #46
Adds a uniform margin to bottom positioned Article Media Content
> Added uniform vertical margin to Article Images in Location Below

- boulderD9_base.libraries.yml
- css/block/events-calendar.css
- css/block/hero-unit.css
- css/block/slider.css
- css/block/text-block.css
- css/block/video-reveal.css
- templates/block/block--inline-block--content-grid.html.twig
- templates/block/block--inline-block--content-row.html.twig
- templates/block/block--inline-block--events-calendar.html.twig
- templates/block/block--inline-block--expandable-content.html.twig
- templates/block/block--inline-block--hero-unit.html.twig
- templates/block/block--inline-block--image-gallery.html.twig
- templates/block/block--inline-block--slider.html.twig
- templates/block/block--inline-block--text-block.html.twig
- templates/block/block--inline-block--video-reveal.html.twig
- templates/paragraphs/paragraph--slider-image.html.twig
All fixes for the basic page blocks
This does not include Admin styling changes as I kept breaking everything trying to do both at once.
Closes #51
Closes #52
Closes #53 
Closes #55 
Closes #56
> All basic page changes

- templates/field/field--field_ucb_article_external_url.html.twig
Resolves #73 - external url articles now auto redirect
> Resolves Article - External Link bug

- boulderD9_base.libraries.yml
> Adding in Roboto font definition

- boulderD9_base.libraries.yml
- css/style.css
- css/ucb-bootstrap-layouts.css
- templates/block/block--inline-block--content-grid.html.twig
- templates/block/block--inline-block--content-row.html.twig
- templates/block/block--inline-block--events-calendar.html.twig
- templates/block/block--inline-block--expandable-content.html.twig
- templates/block/block--inline-block--hero-unit.html.twig
- templates/block/block--inline-block--image-gallery.html.twig
- templates/block/block--inline-block--slider.html.twig
- templates/block/block--inline-block--text-block.html.twig
- templates/block/block--inline-block--video-reveal.html.twig
- templates/content/node--basic-page.html.twig
Initial styles for layout builder bootstrap layouts
Closes #65 
Profile repo PR: https://github.com/CuBoulder/tiamat-profile/pull/14
Project template repo PR: https://github.com/CuBoulder/tiamat-project-template/pull/11
Uses new module: https://github.com/CuBoulder/ucb_bootstrap_layouts
> Issue/65 PR

- css/block/content-grid.css
- css/block/events-calendar.css
- css/block/expandable-content.css
- css/block/hero-unit.css
- css/block/image-gallery.css
- css/block/text-block.css
- css/ucb-bootstrap-layouts.css
- templates/block/block--inline-block--expandable-content.html.twig
- templates/block/block--inline-block--hero-unit.html.twig
- templates/block/block--inline-block--text-block.html.twig
Updated block layouts for the new bootstrap layout builder templates
This PR also removes the "Extra" section from the layout builder
Required PRs
Tiamat Custom Entities: https://github.com/CuBoulder/tiamat-custom-entities/pull/23
UCB Bootstrap Layouts Module: https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/2
Closes #89 
Closes #103 
Closes #104
Closes #106 
Closes #110
> Block layout updates

- boulderD9_base.libraries.yml
- boulderD9_base.theme
- css/style.css
- css/ucb-breadcrumb.css
- templates/layout/page.html.twig
- templates/navigation/breadcrumb.html.twig
- templates/regions/region--breadcrumb.html.twig
> #101 breadcrumb nav fix

- boulderD9_base.theme
- config/install/boulderD9_base.settings.yml
- templates/regions/region--breadcrumb.html.twig
CuBoulder/ucb_site_configuration#2
Sister PR in: [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/3)
> Adds theme setting for disabling breadcrumb navigation

- css/ucb-article.css
- templates/field/field--field_ucb_article_content.html.twig
- templates/paragraphs/paragraph--article-content.html.twig
- templates/paragraphs/paragraph--ucb-article-hero.html.twig
Resolves #124
No other repositories modified.
> "Zebra Striped" article page style fixes

- css/ucb-person.css
- templates/content/node--ucb-person.html.twig
- templates/field/field--field-ucb-person-links.html.twig
Resolves #119 
No other repositories modified.
> Person page improvements

- css/block/video-reveal.css
- js/ucb-video-reveal.js
- templates/field/field--media--field-media-image-caption.html.twig
Sibling Repo PRs
https://github.com/CuBoulder/tiamat-custom-entities/pull/25
https://github.com/CuBoulder/tiamat-profile/pull/17
Fixes the video reveal issues laid out in the 
Closes #107 
Closes #108 
Closes #109 
Also fixes media caption/alt text editing issues that needed to be fixed for the video reveal
Closes #130
> Vid reveal fixes + image caption update

- css/block/expandable-content.css
- css/block/text-block.css
- css/ucb-bootstrap-layouts.css
Changes for overlay styles
Closes #129 
Sibling Repos:
https://github.com/CuBoulder/tiamat-project-template/pull/13
https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/3
https://github.com/CuBoulder/tiamat-profile/pull/19
> Overlay style updates

- .github/workflows/draft-release.yml
- .github/workflows/publish-release.yml
- .github/workflows/update-changelog.yml
- css/ucb-person.css
- templates/content/node--ucb-person.html.twig
- templates/field/field--field-ucb-person-department.html.twig
- templates/field/field--field-ucb-person-title.html.twig
> bullet points added to job titles and departments

- boulderD9_base.theme
- config/install/boulderD9_base.settings.yml
- templates/content/node--ucb-article.html.twig
Resolves #136 
Includes:
- `tiamat-theme` - change/136
- `ucb_site_configuration` - change/136
-  `tiamat-custom-entities` - change/136
> Enables site-wide Preferred Date Format and individual override settings on individual Articles

- templates/field/field--field-ucb-article-categories.html.twig
- templates/field/field--media--field-media-image-caption.html.twig
- templates/field/field--node--body--basic-page.html.twig
- templates/field/field--node--field-newsletter-type.html.twig
- templates/field/field--node--field-ucb-related-articles-parag.html.twig
- templates/field/field--paragraph--field-newsletter-article-select.html.twig
- templates/field/field--paragraph--field-newsletter-content-text.html.twig
Closes #172. Main spots to test are with images and the newsletter. There should hopefully be no error messages in the log.
> Bug Fix : log error attributes not attached message

- css/ucb-people-list.css
- js/ucb-people-list.js
> #179 places <select> inside of <label> to create association

- templates/block/block--inline-block--content-grid.html.twig
- templates/block/block--inline-block--content-row.html.twig
- templates/block/block--inline-block--events-calendar.html.twig
- templates/block/block--inline-block--expandable-content.html.twig
- templates/block/block--inline-block--image-gallery.html.twig
- templates/block/block--inline-block--slider.html.twig
- templates/block/block--inline-block--text-block.html.twig
- templates/block/block--inline-block--video-reveal.html.twig
Addition of container class for placement fixes on full width 1 column
Closes #182
> Addition of container classes

- templates/field/field--media--video.html.twig
Resolves #173  - Fixes video embed issue where video sources would display as an image rather than the embedded video
Includes:
- CuBoulder/tiamat-profile (change/173)
- CuBoulder/tiamat-theme (change/173)
> Change: Video Embed Issues Resolved

- css/ucb-article.css
- js/ucb-article-list.js
- templates/content/node--ucb-article.html.twig
- templates/field/field--field_ucb_article_byline.html.twig
> fix byline dot, teaser shift if no image

- boulderD9_base.theme
- js/ucb-related-articles.js
- templates/content/node--ucb-article.html.twig
- Resolves #201 by improving the user-can-edit check
- Adds the redirect URL to the page for users who aren't logged in and have JavaScript disabled
- Fixes JS error with Related Articles
> Changes to articles set to redirect to another URL under the "External Link" tab

- css/ucb-article-list.css
- js/ucb-article-list.js
- templates/content/node--ucb-article-list.html.twig
- Reduce size of thumbnail image to 100px by 100px
- Normalize date format to (Mon. DD, YYYY)
- Trim summary length
- Adjust padding and spacing 
- Adjust the Read more link to be uppercase 
- Add divider to the bottom of each article as a border-bottom
Closes #199
> Article List Formatting Changes and Updates

- css/ucb-people-list.css
- js/ucb-people-list.js
Adds better formatting to  person list.
Closes #219
> Updated people list formatting

- js/ucb-people-list.js
Closes #279.
Adds a summary of the body, if there is no summary field.
> Adds body field to people list

- css/style.css
- templates/field/field--media--field-media-image--image.html.twig
Closes #152.
Adds new image styles to both WYSIWYG and full html fields.
> Image Style additions

- css/ucb-person.css
- templates/content/node--ucb-person.html.twig
Closes #314 
Moves Person's Photo caption underneath Person Photo on Person Page types. 
Also contains : https://github.com/CuBoulder/tiamat-theme/pull/325
> Change: Moves Person Photo caption on Person Page

- css/ucb-people-list.css
- js/ucb-people-list.js
> Change: Uniform Display of Title & Department fields on the different People List Page display options

- css/ucb-person.css
- templates/content/node--ucb-person.html.twig
A pronouns text field has been added to the Person page, allowing a person's pronouns to be displayed below their name.
Resolves CuBoulder/tiamat-theme#315
Sister PR in: [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/49)
> Adds pronouns field to the Person page

- boulderD9_base.info.yml
- boulderD9_base.theme
- css/ucb-people-list.css
- js/ucb-people-list.js
- Adds a "Reset" button which automatically appears when a non-default user filter is selected on a People List page
- Fixes a bug which caused broken default avatar images while previewing a People List page
Resolves CuBoulder/tiamat-theme#312; Author @TeddyBearX
> Adds "Reset" button to People List page user filters

- css/ucb-article-list.css
- js/ucb-article-list.js
Resolves CuBoulder/tiamat-theme#363
> Tweaks style of Article List; fixes image padding on mobile

- boulderD9_base.libraries.yml
- css/block/ucb-article-feature-block.css
- js/ucb-article-feature-block.js
- templates/block/block--ucb-article-feature.html.twig
Adds a new block type: Article Feature. The Article Feature block displays the latest Articles, with Category & Tag filters set by the user much like the Article List page. The first Article displays a large image and summary and the remaining articles displays titles and thumbnails. 
Resolves #318 
Includes:
- `tiamat-theme` => `issue/tiamat-theme/318`
- `tiamat-custom-entities` => `issue/tiamat-theme/318`
> New Block Type: Article Feature

- css/block/image-gallery.css
Closes #382. 
Removes unneeded spacing between images.
> fix spacing in image gallery

- css/block/slider.css
- templates/field/field--block-content--slider.html.twig
Closes #385.
Fixes issue where bottom-content sliders were having issues with animation.
> slider bottom content fix

- css/style.css
- js/ucb-rave-alert.js
Changes the design of the CU Alert to mirror the D7 version.
Resolves #292
> Change Alerts Design

- css/block/slider.css
Closes #383 and #384.
Adds formatting for right overlay captions, removes bottom padding for mobile design, and reduces opacity for the slider.
> Adds right formatting, remove padding and opacity

- css/block/hero-unit.css
- templates/block/block--hero-unit.html.twig
> Change: Adjusts Hero Unit button spacing to 10px

- templates/block/block--content-sequence.html.twig
Closes #418.
Solves an issue with looping with first != '#'.
> loop bug fix

- js/ucb-people-list.js
Closes #419 
Quick, easy fix to the situation in which there is no primary link.
> bugfix when no primary link

- css/block/expandable-content.css
- templates/block/block--expandable-content.html.twig
This update includes bug fixes and stylistic changes to the "Expandable Content" block type to address recent feedback.
Resolves CuBoulder/tiamat-theme#401
Resolves CuBoulder/tiamat-theme#402
Resolves CuBoulder/tiamat-theme#404
Resolves CuBoulder/tiamat-theme#405
Resolves CuBoulder/tiamat-theme#422
> Improves styling of the "Expandable Content" block type

- css/block/hero-unit.css
- templates/block/block--hero-unit.html.twig
Fixed the padding issues for the video background
Closes #428
> Hero unit vid fix

- css/style.css
Update default layout builder styles so that things are readable and useable. These are temporary fixes until gin_lb gets an update.
> Update for LB D10.1 style.css

- css/menu-styles/highlight-styles.css
- css/menu-styles/ivory-styles.css
- css/menu-styles/layers-styles.css
- css/menu-styles/minimal-styles.css
- css/menu-styles/modern-styles.css
- css/menu-styles/rise-styles.css
- css/menu-styles/shadow-styles.css
- css/menu-styles/simple-styles.css
- css/menu-styles/spirit-styles.css
- css/menu-styles/swatch-styles.css
- css/menu-styles/tradition-styles.css
- css/style.css
Resolves CuBoulder/tiamat-theme#437
> Adds visual indication of active navigation menu items

- css/menu-styles/simple-styles.css
Closes #438.
Fixes drop shadow and margin issue in the simple menu style.
> fix for simple style menu issues

- templates/field/field--field-ucb-article-categories.html.twig
- templates/field/field--field-ucb-article-tags.html.twig
Closes #449.
Small change to change the tags and categories to be sorted alphabetically.
> sort alphabetically

- templates/layout/page.html.twig
- templates/navigation/breadcrumb.html.twig
- templates/regions/region--breadcrumb.html.twig
Resolves CuBoulder/tiamat-theme#460
> Hides breadcrumbs on top-level pages

- css/style.css
Closes #461.
Changes the footer to fill up whitespace.
> Footer change

- templates/content/node--basic-page.html.twig
- templates/field/field--node--title--basic-page.html.twig
Removed page title from the basic page theme
Created a field file for the page title so that it has the proper tags and attributes
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/73
Closes #470
> Page title changes

- css/block/hero-unit.css
- templates/block/block--hero-unit.html.twig
- templates/block/block--slider.html.twig
- templates/block/block--video-reveal.html.twig
Updated the templates and some css to accommodate the new edge-to-edge option
Sister PR: https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/16
Closes #471
> Edge-to-edge update

- boulder_base.libraries.yml
- js/expandable-content.js
- templates/block/block--expandable-content.html.twig
Closes #403.
Enables linking to expandable content based on title of the content.
> Linking to Expandable content

- css/block/slider.css
- templates/paragraphs/paragraph--slider-image.html.twig
Closes #476.
Makes sliders in e2e sections to fully extend the width of the section.
> Slider goes e2e in e2e sections

- config/install/boulder_base.settings.yml
Closes #494.
Quick fix to the favicon path
> favicon fix

- css/style.css
Closes #515.
Adds initial styling.
> Add editor style options

- templates/block/block--boulder-base-breadcrumbs.html.twig
- templates/layout/page.html.twig
- templates/regions/region--breadcrumb.html.twig
Updates to breadcrumbs to not display breadcrumb div when there are no items in the div
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/86
Closes #549
> Breadcrumbs updates

- css/ucb-secondary-menu-region.css
- templates/regions/region--secondary-menu.html.twig
Fixes a bug which caused the secondary menu to be improperly aligned to the left when placed above the main navigation. Resolves CuBoulder/tiamat-theme#558
> Fixes secondary menu alignment

- css/menu-styles/highlight-styles.css
- css/menu-styles/ivory-styles.css
- css/menu-styles/layers-styles.css
- css/menu-styles/minimal-styles.css
- css/menu-styles/modern-styles.css
- css/menu-styles/rise-styles.css
- css/menu-styles/shadow-styles.css
- css/menu-styles/simple-styles.css
- css/menu-styles/spirit-styles.css
- css/menu-styles/swatch-styles.css
- css/menu-styles/tradition-styles.css
- css/style.css
- css/ucb-menu.css
- css/ucb-secondary-menu-region.css
- templates/layout/page.html.twig
Closes #551.
Adds button functionality to secondary menu and fixes other small misalignments.
> Secondary Menu Updates

- templates/content/node--newsletter.html.twig
Resolves CuBoulder/tiamat-theme#596
> Fixes error on Newsletter pages

- templates/block/block--video-hero-unit.html.twig
- templates/field/field--block-content--field-headline--video-hero-unit.html.twig
Hero Unit Separation
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/90
Closes #605
> Hero unit separation

- templates/block/block--boulder-base-breadcrumbs.html.twig
- templates/layout/page.html.twig
This render didn't need to be added to the if statement. 
Fixed formatting as well.
Closes #585
> Breadcrumb fix

- css/ucb-article.css
- js/ucb-article-list.js
- templates/content/node--ucb-article.html.twig
- Adds alt text to Article List images.
- Enhances readability and fixes bugs with article title backgrounds.
Resolves CuBoulder/tiamat-theme#616
> Fixes accessibility issues with Article and Article List

- boulder_base.info.yml
- css/style.css
- templates/layout/page--403.html.twig
- templates/layout/page--search.html.twig
- templates/layout/page--user--login.html.twig
- templates/layout/page--user.html.twig
- templates/layout/page.html.twig
Updated theme files to accommodate the change to Claro.
> Claro theme

- templates/content/node--ucb-people-list-page.html.twig
Resolves CuBoulder/tiamat-theme#626
Sister PR in: [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/44)
> Adds label fields for "Department" and "Job Type" on People List Pages

- css/ucb-class-notes.css
- templates/content/node--ucb-class-notes.html.twig
Adjusts permissions for Class Notes, adds optional image field. Resolves https://github.com/CuBoulder/tiamat-theme/issues/622
Includes:
- tiamat-theme => https://github.com/CuBoulder/tiamat-theme/pull/648
- tiamat-profile => https://github.com/CuBoulder/tiamat10-profile/pull/75
- custom-entities => https://github.com/CuBoulder/tiamat-custom-entities/pull/94
> Class Note Enhancements

- templates/block/block--content-list.html.twig
Removes background colors from the Content List
Resolves #651
> Removes background colors from Content List

- css/block/ucb-collections-block.css
- js/ucb-collections-block.js
- templates/block/block--collection-grid.html.twig
Closes #649.
Adds the required fixes to add an indicator for single select list, fix id's showing, and make the block a web component.
> Adds Collection Grid block fixes

- templates/block/block--image-gallery.html.twig
Closes #642.
Quick fix to make image gallery work.
> image gallery bug fix

- css/style.css
Adds default table styles. The issue brought up by kevin seems to be non-replicable and already solved, but should be kept as a note for future issues.
> default table styles

- boulder_base.libraries.yml
- css/block/social-media-icons.css
- templates/block/block--social-media-icons.html.twig
- templates/field/field--field-social-media-email-link.html.twig
- templates/field/field--field-social-media-links.html.twig
Closes #12.
Sister pull request in custom entities at https://github.com/CuBoulder/tiamat-custom-entities/pull/97.
> Updated Social Media Block

- templates/field/field--field_ucb_person_primary_link.html.twig
Fixed pull request for #683.
Fixes twitter link icon for primary links on person page
> Primary Link Twitter Icon

- css/block/expandable-content.css
Resolves CuBoulder/tiamat-theme#682
> Fixes bug with floated items in Expandable Content block

- boulder_base.libraries.yml
- css/style.css
- css/ucb-taxonomy-page.css
- templates/layout/page--taxonomy.html.twig
- [Bug] Headers on Taxonomy pages are now consistent with the site setting.
- [Change] The "Subscribe to x" link has been hidden.
Resolves CuBoulder/tiamat-theme#697
> Updates Taxonomy page styles

- templates/block/block--site-info.html.twig
CuBoulder/ucb_migration_shortcodes#15
Sister PR in: [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/49)
> Updates `block--site-info.html.twig`

- templates/content/node--ucb-article.html.twig
- templates/field/field--field-ucb-article-categories.html.twig
- templates/field/field--field-ucb-article-tags.html.twig
Resolves CuBoulder/tiamat-theme#701
> Resolves an issue causing the category or tag icon to appear if none are visible

- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
Resolves #713 
Should address the condition where too many Articles causing an issue with how JSON:API handles pagination and subsequent API calls in the Article List blocks
> Fixes Infinite Load Article List Blocks

- css/menu-styles/spirit-styles.css
Closes #712.
Small change to fix padding issue for the spirit menu style
> Fix spirit menu style

- css/block/text-block.css
Fixes a CSS bug which caused a video in an otherwise empty text block to go missing.
Resolves CuBoulder/tiamat-theme#741
> Fixes missing video in otherwise empty text block

- templates/field/field--field-bs-background-style.html.twig
- templates/field/field--field-bs-content-font-scale.html.twig
- templates/field/field--field-bs-heading-alignment.html.twig
- templates/field/field--field-bs-heading-style.html.twig
- templates/field/field--field-bs-heading.html.twig
- templates/field/field--field-bs-icon-color.html.twig
- templates/field/field--field-bs-icon-position.html.twig
- templates/field/field--field-bs-icon-size.html.twig
- templates/field/field--field-bs-title-font-scale.html.twig
Needed to add `.content` to the item renders otherwise we get hit with lots of php errors because the attributes are trying to render for each item.
Closes #752
> item render fix

- css/style.css
- templates/content/media.html.twig
Closes #716.
Adds styling for dynamic sizing for images are aligned right or left.
> Image caption fix for long captions

- css/block/video-reveal.css
- js/ucb-video-reveal.js
- templates/block/block--video-reveal.html.twig
Resolves CuBoulder/tiamat-theme#766
> Fixes Video Reveal block video size bug

- css/block/ucb-article-list-block.css
- js/ucb-article-list-block.js
- Fixes bug where more Articles would display than count specifies
- Articles without thumbnails aren't indented (Teaser and Title & Thumbnail styles)
- Adjusts alignment of thumbnails and borders to align to container (Teaser and Title & Thumbnail)
Resolves #799
> Article List Block - Display Fixes

- css/ucb-form-page.css
> Forms: Required Fields indicated by a red asterisk

- css/block/ucb-collections-block.css
- js/ucb-collections-block.js
- templates/block/block--collection-grid.html.twig
This update:
- [Bug] Addresses item positioning for rows with two items. Resolves CuBoulder/tiamat-theme#833
- [Bug] Addresses longer filter labels not wrapping properly. Resolves CuBoulder/tiamat-theme#822
- [Change] Changes font sizes to match D7 Express. Resolves CuBoulder/tiamat-theme#823
- [Bug] Removes JavaScript error for items with no body.
Sister PR in: [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/126)
> Updates Collection Grid block

- css/ucb-issue.css
- templates/paragraphs/paragraph--ucb-issue-section.html.twig
Resolves https://github.com/CuBoulder/tiamat-theme/issues/852
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/855
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/127
> Issue Page: Section Title is now optional

- css/block/block-styles.css
- css/layout-builder-styles.css
> Adjusts spacing between sibling blocks within a column

- css/block/image-gallery.css
- templates/block/block--image-gallery.html.twig
This update:
- Changes Image Gallery block image spacing to be consistent.
- Removes some styles that were redundant to the ones Bootstrap provides.
Resolves CuBoulder/tiamat-theme#854
> Updates Image Gallery block

- boulder_base.theme
- js/ucb-newsletter.js
- templates/content/node--newsletter--email-html.html.twig
Resolves #867 
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/871
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/130
> Newsletter: Moves social links from Node to Newsletter term

- js/ucb-people-list-block.js
- js/ucb-people-list.js
Previously a maximum of 50 People were being displayed on the People List Page and the People List Block. This has been fixed to allow all People existing on a site to be pulled into these Content Types. 
Resolves #830
> People Lists: Allows for more than 50 People

- css/block/ucb-article-feature-block.css
- js/ucb-article-feature-block.js
Adjusts spacing on Article Feature blocks between thumbnail and title. Fixes the secondary Article row so titles don't overlap into the next Article's thumbnail
Resolves #859
> Article Feature: Adjusts spacing

- css/style.css
This update resolves two style issues with sortable tables in Webforms. It:
- [Bug] Corrects the display of drag icons. Resolves CuBoulder/tiamat-theme#786
- [Change] Decreases the font size of the "Show row weights" button. Resolves CuBoulder/tiamat-theme#787
> Adds sortable table style changes

- templates/block/block--hero-unit.html.twig
Resolves #804.
Sister pull requests in https://github.com/CuBoulder/tiamat10-profile/pull/114, https://github.com/CuBoulder/tiamat-custom-entities/pull/132.
> Adds Wallpaper image style to hero units and video reveal

- css/style.css
- css/ucb-search-page.css
Resolves CuBoulder/tiamat-theme#893
> Fixes Search page style regression

- templates/block/block--site-info.html.twig
Resolves CuBoulder/tiamat-theme#911
> Changes `<h5>` to `<h2>` in site footer

- js/ucb-video-reveal.js
- templates/block/block--video-reveal.html.twig
Resolves CuBoulder/tiamat-theme#901
> Updates Video Reveal block to not mute by default

- templates/block/block--content-grid.html.twig
- templates/navigation/menu--social-media-menu.html.twig
Resolves CuBoulder/tiamat-theme#921
> Fixes error occurring when Content Grid items or social media links are linked to a Drupal route

- css/ucb-people-list.css
- js/ucb-people-list.js
This update:
- [a11y] Adds `aria-hidden="true"` to a person photo's link, or person photo th/td in table view. Adds alt text to the person photo.
- [a11y] Adds `aria-live="polite"` to the region containing the list of people after a user selects an option in filters.
- [a11y] Adds `<span class="sr-only">Loading</span>` to describe the loading icon.
- [Change] Updates the email link in table view to only have the text "Email".
- [Change] Updates the social media link matcher to correctly display the icon for x.com URLs, as well as support the same shortened URLs supported by our social media icons block and menu.
- [Bug] Resolves in CSS an issue where the person photo in table view may become unusably small on mobile devices.
Resolves CuBoulder/tiamat-theme#902
Resolves …
> Updates People List Page

- templates/block/block--content-sequence.html.twig
Links to Drupal routes would incorrectly display `internal:` URIs instead of public URLs. This update fixes the bug.
Resolves CuBoulder/tiamat-theme#926
> Fixes a bug with links in Content Sequence blocks

- css/block/hero-unit.css
- css/block/video-reveal.css
Fixes title coloring as well as the extended horizontal scroll bar for hero and video hero.
Sister PR: https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/41
Resolves #918
> Title and Scroll Fix

- templates/regions/region--footer.html.twig
Resolves CuBoulder/tiamat-theme#945
> Fixes blocks not appearing in the Footer region

- templates/block/block--field-block--node--basic-page--title.html.twig
Resolves CuBoulder/tiamat-theme#969
> Fixes page title not being draggable in Layout Builder

- css/block/content-grid.css
- templates/block/block--content-grid.html.twig
[Bug] Resolves CuBoulder/tiamat-theme#965
> Fixes missing padding at the top of Content Grid items

- css/ucb-people-list.css
- js/ucb-people-list.js
Changes the following on the `People List Page`, specifically in "Table" style:
- Makes the email field have screen reader text "Email <personsName>", rather than just "Email"
- Fixes border style of the table
Resolves #974
Resolves #975
> People List: Table style A11y and Style Changes

- templates/layout/page--webform.html.twig
[Bug, Change] Resolves CuBoulder/tiamat-theme#982
> Creates Webform page template

- css/ucb-person.css
- js/ucb-person-article-list.js
- templates/content/node--ucb-person.html.twig
- Article card border size set to `1px`
- Adjusts heading level of the Articles by Person block on a Person Page, from `h3` to `h2`
- Adds a `Read More Articles by <name>` link if >5 Articles by that Person, leading to the Article List taxonomy View to show all the Articles that Person has been set as on the Article's byline field
Resolves #961
> Person Page: Articles by Person Changes

- templates/block/block--video-hero-unit.html.twig
- Restores dragability in Layout Builder.
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/989
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/144
Resolves https://github.com/CuBoulder/tiamat-theme/issues/988
> Video Hero: restores draggability in LB

- js/ucb-collections-block.js
Closes #954. 
Now correctly generates all collection item nodes. It also now limits collection item nodes by selected category filters as well.
> Fix Collection Grid issues.

- css/block/block-styles.css
- css/style.css
- templates/block/block--text-block.html.twig
Adds a new "Alert" style to the Text Block, useful for alerts or notifications on your site.
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/991
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/145
Resolves #880
> Text Block: Adds Alert Block Style

- css/ucb-site-contact-info-footer.css
- templates/regions/region--site-information.html.twig
This update:
- [Change] Allows items in the site primary contact info in the site footer to have a bottom margin.
- [Change] Updates the column layout of the site footer.
- [Change] Adds margin between columns in the site footer in case they wrap on a mobile device.
Resolves CuBoulder/tiamat-theme#985
> Updates site footer

- css/block/video-reveal.css
[Bug] Resolves CuBoulder/tiamat-theme#999
> Removes padding at the bottom of Video Reveal block image

- boulder_base.theme
- css/menu-styles/ivory-styles.css
- templates/navigation/menu.html.twig
Resolves CuBoulder/tiamat-theme#1004
> Adds visual indicator to menu links linking to unpublished content

- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
- js/ucb-article-list.js
- js/ucb-article-slider-block.js
- js/ucb-category-cloud.js
- js/ucb-current-issue-block.js
- js/ucb-issue-archive.js
- js/ucb-tag-cloud.js
- templates/block/block--article-list-block.html.twig
- templates/block/block--ucb-article-feature.html.twig
- templates/block/block--ucb-article-grid.html.twig
- templates/block/block--ucb-article-slider.html.twig
- templates/block/block--ucb-category-cloud.html.twig
- templates/block/block--ucb-current-issue-block.html.twig
- templates/block/block--ucb-tag-cloud.html.twig
- templates/content/node--ucb-article-list.html.twig
- templates/content/node--ucb-issue-archive.html.twig
- Article Grid Block
- Article Feature Block
- Article List Block
- Article Slider Block
- Current Issue Block
- Category Cloud
- Tag Cloud
- Article List Page
- Issue Archive Page
- Previously a more complete Article could finish processing before one that needs additional calls to complete, such as one with a missing summary waiting for the Article body to finish processing (shortening, stripping elements, adding a `...` .) This could lead to an inconsistent order of Articles being displayed, despite a sort filter on the API call and the data coming back in the proper order. The `build` method on these components has been updated so that adding approved articles to the array of `final articles` (after include/exclude/fetching needed pieces/assembly/etc) are rendered in the order they …
> JSON API Consumer Block bug fixes

- css/block/content-list.css
- css/block/events-calendar.css
- css/block/ucb-article-list-block.css
- css/block/video-reveal.css
- css/menu-styles/highlight-styles.css
- css/menu-styles/ivory-styles.css
- css/menu-styles/layers-styles.css
- css/menu-styles/minimal-styles.css
- css/menu-styles/modern-styles.css
- css/menu-styles/rise-styles.css
- css/menu-styles/shadow-styles.css
- css/menu-styles/simple-styles.css
- css/menu-styles/spirit-styles.css
- css/menu-styles/swatch-styles.css
- css/menu-styles/tradition-styles.css
- css/style.css
- css/ucb-article.css
- css/ucb-footer-menu-region.css
- css/ucb-menu.css
- css/ucb-secondary-menu-region.css
Closes #1059.
This changes the breakpoint from 600px to 576px to match bootstrap container values.
> Updated Mobile Menu Breakpoint

- boulder_base.theme
- config/install/boulder_base.settings.yml
- templates/content/node--ucb-article.html.twig
[Remove] Resolves CuBoulder/tiamat-theme#1073
Sister PR in: [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/55)
> Removes "social share position" setting

- templates/block/block--content-list.html.twig
> Content List: makes URLs absolute

- css/style.css
Closes #1096.
Adds the dark styling to urls and links.
> Add styling for webform urls

- css/ucb-person.css
- js/ucb-person-article-list.js
- templates/content/node--ucb-person.html.twig
- templates/field/field--field-ucb-person-department.html.twig
Closes #1098.
Changes the person page to match the new template provided.
> Redesign of person page

- boulder_base.libraries.yml
- css/block/expandable-content.css
- css/ucb-accordion-styles.css
- templates/block/block--expandable-content.html.twig
These edits were made to make our current expandable/accordion styles more generic/global so that they would affect both the expandable block and the new accordion button that Tim made.
Resolves #1106
> Updates accordion styling

- css/block/hero-unit.css
- js/ucb-hero-unit.js
Closes #1088.
This limits the height of the video hero unit in the edge-to-edge case. This also centers all videos to make their quality higher in all cases.
> Video Hero Unit Height Updates

- css/style.css
Helps close https://github.com/CuBoulder/tiamat10-profile/issues/155.
Adds the necessary css to enable the column list styles.
Sister PR in: https://github.com/CuBoulder/tiamat10-profile/pull/158/.
> Column List Style for WYSIWYG

- js/ucb-menu.js
Closes #1136.
This adds extra checks to the mobile menu to eliminate errors.
> Mobile Menu Error fix

- js/ucb-hero-unit.js
Closes #1140.
Corrects the functionality for the video hero unit for vimeo videos.
> Video Hero Unit vimeo error fix

- templates/regions/region--site-information.html.twig
This update:
- [change, security] Changes HTTP to HTTPS in some links in the site footer. Resolves CuBoulder/tiamat-theme#1114
- [change] Removes a few special characters from the HTML source and replaces them with their HTML counterparts.
> Updates site information region

- js/ucb-person-article-list.js
- templates/content/node--ucb-person.html.twig
- Previously this block would throw an API error on multisites due to an error in the API endpoint not being adjusted for a multisite config and it would attempt to fetch a relative API path. This has been corrected. 
- Fixes the links to add the base URL as well for correct Article linking and linking to the correct authors Articles List page for 5+ Articles.
Resolves #1116
> Articles by Person: Fixes API Error and Multisite lniks issue

- css/block/slider.css
- templates/block/block--slider.html.twig
This update:
- [Bug] Ensures Slider block styles are applied only to the Slider block. Resolves CuBoulder/tiamat-theme#1148
- [Change] Corrects indentation and code readability issues in the Slider block template and stylesheet.
> Updates Slider block

- templates/content/node--newsletter--email-html.html.twig
Resolves breaking image bug with Newsletters along with some header spacing cleanup due to template conditionals
Resolves #1133
> Newsletter: Broken Images and Header Cleanup 

- css/layout-builder-styles.css
- css/style.css
- css/ucb-class-notes.css
- css/ucb-menu.css
- css/ucb-person.css
- templates/content/node--ucb-class-notes.html.twig
Sidebar and Title spacing changes are fixed so that they align. The Title's container is what is aligned properly rather than the text in most cases as the font has a line-height that adds a little more padding around the text. Kevin wants the containers aligned and less focus on aligning the text.
Resolves #1128 
Resolves #1129
> Sidebar/Title Spacing Fixes

- js/ucb-article-list.js
Previously an `Article List Page` could sometimes display `Articles` out of chronological order. This issue was due to the asynchronous nature of the chained API calls, which could cause `Articles` that required additional processing (e.g., generating a summary from the article body) to be placed out of order after processing completed as other earlier, more complete `Articles` "finished" before them.
Now, all `Articles` are processed and appended to the page in their original order, ensuring the chronological display of articles. 
Note: This did not seem to affect the other `Article List` style blocks, only the `Article List Page`
Resolves #1176
> Article List: Chronological Order

- boulder_base.libraries.yml
- css/block/ucb-slate-form.css
Styles the submit button similar to the Form Block
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1173
Related: https://github.com/CuBoulder/tiamat-custom-entities/pull/156
> Slate Form: Styles Submit Button

- boulder_base.theme
This update:
- [change] Adds "University of Colorado Boulder" to the end of page titles. It first checks if the site is already called that to prevent this text from being duplicated on the home page. Resolves CuBoulder/tiamat-theme#1188 
- [change] Cleans up PHPCS errors in `boulder_base.theme`.
> Adds "University of Colorado Boulder" to the end of page titles

- css/ucb-accordion-styles.css
An issue existed with incorrect sizing and spacing between the icon and text of an accordion item header if the text had wrapped. This update resolves the issue.
[bug] Resolves CuBoulder/tiamat-theme#1192
> Fixes uneven accordion icon spacing

- css/ucb-article-dark.css
- templates/field/field--field_ucb_article_byline.html.twig
Adjusts the byline display so it links to the connected Person Page, using the connect page on the byline's field `Author Person Page`.
Resolves #1220
> Articles: Bylines link to their respective connected Person Pages

- templates/block/block--slider.html.twig
This update modifies `Slider` blocks to Autoplay, advancing slides every 7 seconds. On hover, the autoplay is paused. Previously Sliders did not autoplay. 
Resolves #1202
> Sliders: Autoplay On and Pause Functionality

- boulder_base.info.yml
- templates/field/field--block-content--field-calendar-code.html.twig
Remove `|raw` loading.
Replace localist widget ID with randomly generated ID Strip query strings from embed input.
Hardcode embed div and js using new ID and query parameters
Resolves #842
> Events Calendar |raw removal

- css/ucb-taxonomy-page.css
- templates/layout/page--403.html.twig
- templates/layout/page--node--layout.html.twig
- templates/layout/page--search.html.twig
- templates/layout/page--taxonomy.html.twig
- templates/layout/page--user--login.html.twig
- templates/layout/page--user.html.twig
- templates/layout/page--webform.html.twig
- templates/layout/page.html.twig
[bug] Resolves CuBoulder/tiamat-theme#1263
> Adds sidebar region to taxonomy pages

- boulder_base.libraries.yml
- css/ucb-pager.css
- css/views/views-mini-pager.html.twig
[bug, change] Resolves CuBoulder/tiamat-theme#1262
> Styles pager on Taxonomy pages

- README.md
- boulder_base.info.yml
- boulder_base.theme
- config/install/boulder_base.settings.yml
- css/ucb-user-page.css
- templates/layout/page--user.html.twig
[new] Resolves CuBoulder/tiamat-theme#1274
> Adds `web_express_version` theme variable

- templates/block/block--social-media-icons.html.twig
[bug] Resolves CuBoulder/tiamat-theme#1295
> Corrects Social Media Icons block to not be inline

- css/block/block-styles.css
[bug] Resolves CuBoulder/tiamat-theme#1267
> Fixes link color on alert-style text blocks

- templates/content/node--ucb-person.html.twig
> Person Page: Corrects 'Articles by Person' Section Full Name Missing Space

- js/ucb-video-reveal.js
Resolves #1334. 
Removes the console log from the video reveal
> Remove console log from video reveal

- css/style.css
- templates/form/form-element.html.twig
[bug] Resolves CuBoulder/tiamat-theme#1318
> Corrects spacing issue for checkboxes and radio buttons on webforms

- css/ucb-article.css
[change, minor] Resolves CuBoulder/tiamat-theme#1331
> Adds padding below article title background on articles

- css/ucb-person.css
- templates/field/field--field-ucb-person-primary-link.html.twig
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1337
> Fixes styling issues of social links on the person page

- css/ucb-article.css
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1358
> Removes padding below article title image header and changes to margin

- boulder_base.theme
Image position needed checks for if the route was in preview or not for the proper node id.
Resolves #1361
> Fix Preview Error

- css/block/ucb-mega-menu.css
- templates/field/field--field_mega_menu_links_desc.html.twig
- templates/field/field--field_mega_menu_text_above.html.twig
Resolves #1348.
Changes the mega menu descriptions to take up the full width of its area.
> Mega menu changes for Description

- css/menu-styles/highlight-styles.css
- css/menu-styles/ivory-styles.css
- css/menu-styles/layers-styles.css
- css/menu-styles/minimal-styles.css
- css/menu-styles/rise-styles.css
- css/menu-styles/shadow-styles.css
- css/menu-styles/swatch-styles.css
- css/menu-styles/tradition-styles.css
- css/ucb-secondary-menu-region.css
Resolves #1367.
Adds a new style for the buttons in the secondary menu.
> Secondary menu button appearance rework

- templates/block/block--aggregator-feed-block.html.twig
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1366
> Corrects padding and icon of Aggregator Feed block

- css/block/ucb-article-list-block.css
- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
- js/ucb-article-list.js
Previously when an Article aggregator block had a missing `summary` field, a summary using the `body` field would be generated as a substitution it could result in HTML entities and special characters showing up incorrectly, such as `&nbsp` and `&amp`.  This has been corrected.
This affects the following blocks: `Article List Block`, `Article Grid Block`, `Article Feature Block` as well as the `Article List Page` Content type. 
Resolves #1386
Resolves #1351 
---
Previously `Article List Blocks` set to Feature Wide Image display had a height limitation, which would display the wide image style incorrectly. This has been adjusted to maintain proportions, mirroring D7
Resolves #1390
> Article Aggregators: Fixes Summary Generation of handling special characters and HTML entities. Additional Article List Block Image fixes.

- css/style.css
- css/ucb-site-contact-info-footer.css
This update:
- [bug, severity:minor] Forces Site Contact Info Footer block to occupy the full available width. Resolves CuBoulder/tiamat-theme#1394
- [bug, severity:minor] Fixes alignment of styled blocks in the Site Information region. Resolves CuBoulder/tiamat-theme#1395
> Corrects minor layout problems in the site footer

- css/style.css
- css/ucb-menu.css
- js/ucb-mega-menu.js
- js/ucb-menu.js
- templates/layout/page.html.twig
- templates/regions/region--footer.html.twig
Resolves #1120.
Adds styling for the footer and after content regions for menus to be added.
> Menu Styles for Footer and After Content regions

- templates/layout/page.html.twig
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1409
> Google Translate: Adds Japanese and Tibetan language options to sites

- css/layout-builder-styles.css
- css/ucb-menu.css
Fixes spacing issues for blocks in above and below content.
Also adds proper stacking for menus in different regions
Resolves #1407
> Responsive menus in the below content regions 

- css/block/content-list.css
Update basic teaser max width for teasers to 100px like D7 
Have teaser max width be 50px
Resolves #1349
> Update content list teaser image sizing

- css/ucb-search-box.css
- templates/includes/ucb-search-box.html.twig
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1413
> Fixes radio button / label alignment in search modals

- js/ucb-hero-unit.js
Resolves #1352.
Makes the video hero more vertically centered
> Make video hero vertically centered

- css/ucb-menu.css
- js/ucb-mega-menu.js
- js/ucb-menu.js
Resolves #1408.
Removes the double borders on menus in the above and below content regions.
> Remove double borders on menus

- templates/content/node--ucb-person.html.twig
Resolves #1388.
Adds a conditional based on the images and information fields to decide on the design of the person page.
> Add conditions for person pages with no images

- templates/layout/page.html.twig
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1420
> Adds `clearfix` for main content region

- css/style.css
[change] Resolves CuBoulder/tiamat-theme#1444
> Adds spacing between items in a no-bullet list

- css/block/ucb-collections-block.css
- js/ucb-collections-block.js
Resolves #1439 and #1446.
Adds a condition for the collection items to be published, and adds a condition to force the columns to always be equal length.
> Collection Grid Fixes

- css/block/content-list.css
Fixes text wrapping of the text on Sidebar display. Text will remain all on one row with the thumbnail image.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1169
> Content List: Fixes the sidebar display's text

- css/style.css
Change the black variable from `#222` to `#000`
Resolves #1478
> Back to Black

- css/menu-styles/highlight-styles.css
- css/menu-styles/shadow-styles.css
Fixes some menu style issues in the shadow and highlight styles.
Removes the gap in the highlight style and lowers the text in the shadow style.
> Updated menu style fixes

- js/ucb-class-notes-list.js
Previously special characters from Class Notes wouldn't escape properly, such as `&nbsp`. They are now correctly decoded.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1518
> Class Notes List: special character fixes

- js/ucb-expandable-content.js
- templates/navigation/menu--extras.html.twig
Resolves #1536
Removes all mentions to menus and the functionality of a hash being added to menus.
> Remove all menu hashes

- boulder_base.libraries.yml
Additional work to get the CSS files loading the proper order after the 10.4 update.  
Among other issues will resolve #1577
> Adjusting weights for CSS files and removing weights from JS libraries

- css/ucb-article.css
- templates/paragraphs/paragraph--article-secondary-content.html.twig
Added new paragraph template for secondary article content.
Updated css on articles so that content isn't justified and aligned for everything, just blockquotes
Resolves #1597 
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/200
> New Article Paragraph

- boulder_base.libraries.yml
- js/ucb-form-page.js
Think this is the culprit behind broken forms -- need to test to see what config we enabled just to work around this issue-casuing bit of code can stay and what can go from `profile`
> Remove stray JS that breaks forms

- css/block/ucb-content-sequence.css
Add white background color to content sequence cards so they aren't transparent on background images.
Resolves #1611
> Background color addition

- css/block/ucb-content-sequence.css
Updated the content sequence text card colors so that they are standardized.
Cards are only white backgrounds so colors can be hard set rather than changing depending on background/frame colors
Resolves #1643
> Content sequence card colors
