CuBoulder/tiamat-theme

- js/ucb-related-articles.js
Resolves #85, (bug-85) to immediately restore functionality of the Related Articles block on the Safari browser.
Related Articles block refactor moved into separate issue ticket #86 for further development
> Fixes Safari issue with variable declaration scoping

- css/style.css
> #135 Resets Bootstrap’s `placeholder` class styles

- templates/block/block--ucb-campus-news.html.twig
This is a fix for a margin issue with the #82 Campus News Block introduced in the latest theme update.
Related PRs: [tiamat-project-template](https://github.com/CuBoulder/tiamat-project-template/pull/14), [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/20)
> #82 fixes campus news block margins

- .github/workflows/draft-release.yml
- .github/workflows/publish-release.yml
- .github/workflows/update-changelog.yml
- css/ucb-people-list.css
- css/ucb-person.css
- js/ucb-people-list.js
- templates/block/block--ucb-campus-news.html.twig
- templates/content/node--ucb-people-list-page.html.twig
- templates/content/node--ucb-person.html.twig
- templates/field/field--field-ucb-people-department.html.twig
- templates/field/field--field-ucb-people-filter-1.html.twig
- templates/field/field--field-ucb-people-filter-2.html.twig
- templates/field/field--field-ucb-people-filter-3.html.twig
- templates/field/field--field-ucb-people-job-type.html.twig
- templates/field/field--field-ucb-person-department.html.twig
- templates/field/field--field-ucb-person-title.html.twig
Resolves #120 - Enhances People List Page design
Authored by @TeddyBearX and @patrickbrown-io 
Includes: 
-  Adds taxonomy terms for "Filter 1", "Filter 2", "Filter 3"
-  Adds fields for "Filter 1", "Filter 2", "Filter 3"
-  The bio field on the person page has a summary option they can use (or ignore if they want to leave it blank)
-  Adds fields for filtering by "Filter 1", "Filter 2", "Filter 3"
-  Adds toggles for enabling filters to be user-accessible
-  "Child Terms" option
-  Refactored as web component
-  Fixed no photo bug
-  The list view displays name, photo, job title(s), department, email, and phone number. and summary of bio field.
-  JavaScript and CSS UI for user-accessible filters
> Change: People List Page Design

- boulderD9_base.libraries.yml
- js/livechat.js
- js/mainstay.js
- js/statuspage.js
- templates/block/block--includes-block.html.twig
- templates/layout/page.html.twig
This is a major update to CU Boulder Site Configuration. Changes include:
- A new CU Boulder site settings administration menu (`/admin/config/cu-boulder`) with three separate pages: Appearance, Contact info, and Third-party services
- Three new permissions for accessing and editing the settings on these pages
- Version bump to indicate D10 compatibility
Authors:
- @TeddyBearX (custom entity, permissions, and menu structure)
- @patrickbrown-io (frontend and third-party service compatibility)
Sister PR in: [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/6)
Third-party services is a new entity-based way to manage client-side services on a site. The services supported are:
- Mainstay (AKA Admithub)
- LiveChat
- StatusPage
These services can be configured and …
> Major changes to Site Configuration bring new permissions and third-party services settings

- boulderD9_base.libraries.yml
- css/block/aggregator-feed.css
- templates/block/block--aggregator-feed-block.html.twig
This update installs and themes the Aggregator module and Aggregator feed block respectively. The block is available to be placed on a basic page via Layout Builder.
Sister PRs in: [tiamat-project-template](https://github.com/CuBoulder/tiamat-project-template/pull/18), [tiamat-profile](https://github.com/CuBoulder/tiamat-profile/pull/23)
Resolves #169
> Adds Aggregator module and feed block

- css/style.css
- css/ucb-page.css
- templates/field/field--media--field-media-image--image.html.twig
Added some padding around images that have been placed with CKEditor in Text Blocks.  
Closes #153, works on both articles and basic pages
> Spacing around images in content

- js/ucb-article-list.js
Previously if an Article set to display on an Article List page does NOT contain any content, Article List would stop mid-render and display "Error retrieving article list from the API endpoint. Please try again later."  This was a possibility for Articles using the external url feature.
This issue has been resolved on the Article List for any Articles that provide no content (such as External URL Articles) and Article List renders normally
Resolves #200
> Resolved Article List bug caused by Articles that have no content

- css/style.css
Images were left-aligned even when specified to be centered when placed from the media library via the CKEditor interface.  
Captions are not being honored either, however this seems to be an issue with CKEditor 5 and the Drupal Media Library.  Should be fixed in a future version of Drupal : (see : https://www.drupal.org/project/drupal/issues/3246385 ) 
Closes : #205
> Fix for center-align images placed via CKEditor

- js/ucb-related-articles.js
- templates/field/field--field-ucb-article-categories.html.twig
- templates/field/field--field-ucb-article-tags.html.twig
Category and Tag taxonomies receive the form option for them to be hidden from public view, but the terms are still available for administration.
- Articles tagged with a private term can still be used to group those articles within Article Lists.
- Private terms are NOT used in the Related Articles block - private taxonomies do not affect an Articles 'related-ness' scores
- Private terms will not display in the Category/Tag link section on Articles
Resolves #217 
Change Includes:
- `tiamat-theme` => `issue/217`
- `tiamat-custom-entities` => `issue/217`
> Hidden Terms: Categories and Tags recieve form option to toggle display for admin-only taxonomies

- boulderD9_base.theme
- config/install/boulderD9_base.settings.yml
- css/ucb-site-contact-info-footer.css
- templates/block/block--site-info.html.twig
- templates/layout/page.html.twig
This update:
- Adds an _Advanced_ view at the bottom of the _Appearance_ settings, collapsed by default and visible only to those with the _Edit advanced site settings_ permission.
- Moves all theme settings previously restricted to Drupal's default theme settings into the _Advanced_ view.
- Adds site-specific custom logos (resolves CuBoulder/tiamat-theme#264) and places the settings for custom logos into the _Advanced_ view:
- Custom logo requires _white text on dark header_ and _dark text on white header_ variants.
- An image can be uploaded or a path can be manually specified for each.
- ~~A scale can be specified, which defaults to _2x_ (Retina) but also allows _1x_ (standard) or _3x_ (enhanced Retina)~~.
- Assigns the _Architect_ and _Developer_ user roles the _Edit advanced site …
> Adds "Advanced" appearance settings and custom site logos; modifies contact info settings

- css/block/hero-unit.css
- css/style.css
- templates/block/block--hero-unit.html.twig
Added extra css class to attributes for hero unit (will need to assess for other inline blocks and blocks) Added `img` to the style.css with the `article img` because images in block layout aren't given the `article` wrapping tag which caused problems with responsive images.
Closes #298
> Fix hero unit and image sizing

- boulderD9_base.info.yml
- css/ucb-person.css
- templates/content/node--ucb-person.html.twig
- templates/field/field--field-ucb-person-address.html.twig
- templates/field/field--field-ucb-person-department.html.twig
- templates/field/field--field-ucb-person-email.html.twig
- templates/field/field--field-ucb-person-first-name.html.twig
- templates/field/field--field-ucb-person-last-name.html.twig
- templates/field/field--field-ucb-person-links.html.twig
- templates/field/field--field-ucb-person-phone.html.twig
- templates/field/field--field-ucb-person-photo.html.twig
- templates/field/field--field-ucb-person-pronouns.html.twig
- templates/field/field--field-ucb-person-title.html.twig
- Some special characters such as `&` in _Job Title_ and _Department_ fields displayed as `&amp;` on Person pages. These characters now display properly. Resolves CuBoulder/tiamat-theme#275
- An error resulted from the added `core/drupalSettings` dependency. This dependency is removed.
- Person page schema changes: `itemprop` attributes have been move into field templates; `itemscope` moved to the higher-level `<article>` tag.
- Additional cleanup of the Person page template
> Fixes a bug which caused improper display of special characters like ampersands on Person pages

- js/ucb-article-list.js
Resolves #361 -- Refactors render to use `innerText` instead of `innerHTML` to assemble list render, protecting from malicious user input
> Refactor to escape HTML from Article user input on Article List

- css/ucb-article-list.css
- js/ucb-article-list.js
- templates/content/node--ucb-article-list.html.twig
The Article List page now uses a button to address accessibility concerns when loading more Articles, instead of a scroll-based 'infinite loader'. The button only appears if additional Articles are available via JSON API
Resolves #370 , also resolves #238
> Change: Article List adds button to load more Articles for improved accessibility 

- css/block/content-row.css
- templates/block/block--content-row.html.twig
Updated the feature option of the content rows block. Features are now a 60/40 split, width and sizing works properly. Removed the 20px bottom padding from the newer image styles update.
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/61
Closes #380
> Updated feature settings

- templates/block/block--content-list.html.twig
- templates/block/block--text-block.html.twig
A Content List block may have failed to update properly after updating a referenced node. A Content List or Text block placed using Block Layout may have also failed to reflect changes made to the block's fields. This update includes a fix to prevent stale cache issues.
Resolves CuBoulder/tiamat-theme#377
Resolves CuBoulder/tiamat-theme#378
Resolves CuBoulder/tiamat-theme#387
> Fixes Content List and Text block stale cache issues

- templates/block/block--hero-unit.html.twig
Hero Unit buttons correctly link when provided internal links either by direct internal url or selected by page title within the form. 
Resolves #407
> Hero Unit Buttons fixed for Internal Links

- css/block/events-calendar.css
- templates/block/block--events-calendar.html.twig
Resolves #381 - Adds a Link field to the Events Calendar Block to allow for links to additional events. 
Includes:
[tiamat-theme](https://github.com/CuBoulder/tiamat-theme) => [issue/tiamat-theme/381 ](https://github.com/CuBoulder/tiamat-theme/pull/411)
[tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities) => [issue/tiamat-theme/381](https://github.com/CuBoulder/tiamat-custom-entities/pull/65)
> Adds Link field to Events Block

- css/ucb-article.css
- templates/content/node--ucb-article.html.twig
Resolves #348  - Changes Article Taxonomy term display style. Terms are no longer be all uppercase and icon flush with first term. Color changes to icons.
> Change: Article Taxonomy term display style

- css/block/text-block.css
- templates/block/block--text-block.html.twig
Adds a White background option to card-style Text Block for the case where sections have a different colored background
Includes:
- `tiamat-theme` => `issue/tiamat-theme/413`
- `tiamat-custom-entities` => `issue/tiamat-theme/413`
Resolves #413
> Change: Adds 'White' background to card-styled Text Block

- boulder_base.theme
- templates/content/node--basic-page.html.twig
- templates/content/node--form-page.html.twig
- templates/content/node--how-to-page.html.twig
- templates/content/node--newsletter.html.twig
- templates/content/node--ucb-article-list.html.twig
- templates/content/node--ucb-article.html.twig
- templates/content/node--ucb-issue-archive.html.twig
- templates/content/node--ucb-issue.html.twig
- templates/content/node--ucb-people-list-page.html.twig
- templates/content/node--ucb-person.html.twig
Resolves #448 
Sets the title of pages chosen to be the site's default front page to 'sr-only' class. Will hide the title visually but still accessible to screen readers. Currently this works only if the page is set to explicitly the default '/homepage'.
> Page Title on user-set default Front Page set to screen-read only

- templates/block/block--content-row.html.twig
This update enables the creation of Content Row blocks with image-less content and displays it correctly in the "Teasers" and "Teasers Alternate" layouts.
Resolves CuBoulder/tiamat-theme#453
Sister PR in: [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/71)
> Removes image requirement from Content Row "Teaser" layouts

- boulder_base.info.yml
- boulder_base.theme
- templates/layout/page.html.twig
- templates/regions/region--footer.html.twig
- templates/regions/region--site-information.html.twig
Added new regions to to .info
Added new region rendering to page
Changed where the slogan is displayed in .theme
Added new `site-information.html.twig` for new region where slogan is displayed
Updated `footer.html.twig` to iterate through content so that it automatically adds columns (up to 4 per row)
I left our current machine names for items like `left_sidebar` the same but changed their display names to match the ones given by Kevin to `Sidebar First`
We also have logic written in the page.html.twig in case two sidebars are made through the block layout. Currently the settings only allow for one though.
I have left social media menu and footer menu as regions for the time being because I think those need to be separate for menuing purposes at the moment. 
Sister PR: …
> Re-factor of Drupal Regions to more closely match D7 Express

- css/style.css
Closes #27 and #350 .
Adds the css needed for the profile installations changes for the taxonomy views.
> Styling for taxonomy term views

- css/block/hero-unit.css
- templates/block/block--hero-unit.html.twig
Fixed the hero unit videos to work/fit properly in the new layout builder settings. Added "Size Priority" as an option to hero units so that we can have 100vh sections. Video now uses the 100vh by default because otherwise it's crazy ugly (can be easily changed now that I've refactored some of the css)
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/74
Closes #481
> Hero unit work

- css/style.css
- templates/content/media.html.twig
Conditionally removes extra `<div>` elements added through Twig when there's no attributes to justify an additional `<div>` wrap of the rendered content. 
Changes default div styling of the imageMediaStyle class to not be `display:block`, both of which caused issues with wrapping an image in an anchor tag making the entire row clickable rather than just the image.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/522
> Remove Extra Markup from inserted Images

- css/style.css
This change aligns the list indicators on a list element with other text elements next to a left-aligned image. 
Previously, the float css for aligning an element left would cause visual issues with list indicators specifically, the bullet-point or numbering becoming hard to see or lost within the image. There is now condtionally applied left-spacing to rendered Ordered and Unordered list elements, when directly next to a Left Align (.align-left) image. 
Resolves #523
> Fixes List Indicator Alignment with Left Align Images

- boulder_base.libraries.yml
- css/style.css
- css/ucb-brand-bar.css
- css/ucb-search-box.css
- css/ucb-search-modal.css
- js/ucb-search-box.js
- js/ucb-search-modal.js
- templates/includes/ucb-search-box.html.twig
- templates/includes/ucb-search-modal.html.twig
- templates/layout/page.html.twig
This update:
- Adds a search modal which appears when clicking on the search icon in the top bar.
- Adds a new "Pages and search" tab to CU Boulder site settings (`/admin/config/cu-boulder/pages`). This tab contains settings accessible to Architect, Developer, and Site Manager:
- The home page setting (moved from "General").
- Options to enable site search, all of Colorado.edu search (default), both, or neither.
- Configuration for the site search label, placeholder, and URL.
- Renames "Appearance" to "Appearance and layout" and alters the descriptions of menu items.
- Adds the [Google Programmable Search Engine](https://www.drupal.org/project/google_cse) module, which allows creating custom search pages to use with site search.
Resolves CuBoulder/tiamat-theme#266
Sister PR in: …
> Adds search frontend and settings

- templates/layout/page--user.html.twig
- templates/layout/page.html.twig
Closes #525.
Adds the menu styles to the user page.
> Adds menu styles to the user page

- boulder_base.libraries.yml
- css/ucb-menu.css
- templates/block/block--system-menu-block.html.twig
- templates/layout/page.html.twig
- templates/navigation/menu.html.twig
This update completes in-content menu blocks (menu blocks placed outside of a navigation bar, e.g. in a sidebar) by styling them and adding the [Menu Block](https://www.drupal.org/project/menu_block) contrib module for additional options.
Sister PR in: [tiamat10-project-template](https://github.com/CuBoulder/tiamat10-project-template/pull/25), [tiamat10-profile](https://github.com/CuBoulder/tiamat10-profile/pull/50), [ucb_admin_menus](https://github.com/CuBoulder/ucb_admin_menus/pull/13)
Resolves CuBoulder/tiamat-theme#267
Resolves CuBoulder/tiamat-theme#528
> Completes in-content menu blocks

- config/install/boulder_base.settings.yml
- templates/content/node--ucb-people-list-page.html.twig
Changes the People List `Filter 1`, `Filter 2`, and `Filter 3` custom labels to a Global Setting in Site Configuration, rather than being set per-page. These labels will be set under Configuration => Cu Boulder Site Settings => Appearance and Layout.
Resolves #543 
Includes:
- `ucb_site_configuarion` => https://github.com/CuBoulder/ucb_site_configuration/pull/35
-  `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/560
-  `ucb_custom_entities` =>
> People List Filter Labels as a Global Setting

- css/ucb-article.css
Corrects styles for `Article Title Background` with Overlays (under Advanced Style Options on Article Nodes)
Resolves #566
> Corrects Article Title Background Image display issues

- config/install/boulder_base.settings.yml
- templates/content/node--ucb-article.html.twig
- templates/content/node--ucb-people-list-page.html.twig
This update:
- Moves all settings from "Pages and Search" into "General". Search settings are now advanced settings.
- Replaces the "Pages and search" and "Related articles" tabs with a brand new "Content types" tab. All "Related articles" settings have been moved into "Content types".
- Replaces the `edit ucb pages` and `configure ucb related articles` permissions with a new `edit ucb content types` permission.
- Moves the People List filter labels and Article date format into "Content types".
- Moves the GTM account setting into "General" as an advanced setting.
CuBoulder/ucb_site_configuration#36
Sister PR in: [ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/38), [tiamat10-profile](https://github.com/CuBoulder/tiamat10-profile/pull/53)
> CU Boulder Site Configuration 2.6

- boulder_base.libraries.yml
- css/ucb-search-page.css
- templates/layout/page--search.html.twig
Resolves CuBoulder/tiamat-theme#535 – A site's search page created using the [Google Programmable Search Engine](https://www.drupal.org/project/google_cse) module is now styled properly. Correct settings for the search page (may already be defaults):
- Display Drupal-provided search input: **✓**
- Display search results: **On this site (requires JavaScript)**
- Layout of Search Engine: **Results only**
"Display Google watermark" is on for D7 Express and works fine here too, whether to enable it is a possible future topic of discussion.
> Styles search results page

- css/block/ucb-article-slider-block.css
- js/ucb-article-slider-block.js
- Adds condition where 6 articles filtered 'good' but additional articles available (10+ which triggers JSON API pagentation), this previously failed to render.
- Fixes console error related to innerText (Removed old code for generating a Date and Body)
- The thumbnail image now uses `Focal Image Wide` rather than `Focal Image Square`
- Spinning Loader is centered on the block
Resolves #580
> Fixes Article Slider Bugs + Style Refinements

- templates/navigation/menu--social-media-menu.html.twig
Social Media Menu is now icons only, fixes bug where the site name would display. Fixes spelling of 'Facebook'.
There was a: `<span class="vertical-icon-span"> * _siteNameHere_ * </span>`  on the template that was causing the site names to appear next to the respective logo on each link in the social media menu. These spans did not appear to be used anywhere else in d10, so they were removed to resolve the issue.
Resolves #586
> Social Media Menu - Now Icons Only

- css/block/events-calendar.css
Adjusts the `Events Calendar` so it matches the background color of the section it is placed in, rather than being always white. Text color adjusted to white for black and dark gray section backgrounds. 
@jcsparks - Let me know if gold section background needs some text color adjustments, I could make an override for that that makes the text a darker gray / black than the default. 
Resolves #564
> Events Calendar Background matches Section background color

- templates/content/node--form-page.html.twig
The Form Page node's body displays above the attached form.
Resolves #599
> Form Page - Adds Body Field

- boulder_base.theme
- templates/field/field--node--title--basic-page.html.twig
This fixes the functionality where a title is hidden when set as the site's homepage. This was previously working before a moveable title refactor and has been corrected.
Resolves #607
> Title on Homepage no longer visible

- templates/block/block--expandable-content.html.twig
Resolves CuBoulder/tiamat-theme#614
> Fixes expandable content `aria-expanded` errors

- css/style.css
- templates/layout/page--403.html.twig
- templates/layout/page--search.html.twig
- templates/layout/page--user--login.html.twig
- templates/layout/page--user.html.twig
- templates/layout/page.html.twig
Fixes for the `layout-container` and local-tasks css
> Claro theme mini-update

- boulder_base.info.yml
- boulder_base.theme
- config/install/boulder_base.settings.yml
- templates/layout/page.html.twig
Resolves CuBoulder/tiamat-theme#633
Sister PR in: [tiamat10-profile](https://github.com/CuBoulder/tiamat10-profile/pull/77), ~~[ucb_site_configuration](https://github.com/CuBoulder/ucb_site_configuration/pull/45)~~
> Updates sidebar regions

- js/ucb-people-list-block.js
- js/ucb-people-list.js
- templates/block/block--ucb-people-list-block.html.twig
- templates/content/node--ucb-people-list-page.html.twig
- templates/field/field--field-ucb-person-links.html.twig
- templates/field/field--field_ucb_person_primary_link.html.twig
Provides the following bug fixes to the `People List Block` and the `People List Page`
- Fixes a bug with internal links throwing an error. Adjusts so internal links will convert to absolute pathing, which should allow for our multi-site, single domain sites to use internal links. 
- No termId present on a Person causing a JavaScript error preventing a full render. Was able to cause this error with multiple people and one without any terms attached. This error was present on both `People List Page` and `People List Block`.
- Swaps Twitter's bird to Twitter's X... ( X 's X?)...whatever you want to call it, the bird icon is now an X icon.
- No terms existing for a taxonomy, and the `People List Page` having that taxonomy selected for `Group By` caused a white screen and no errors. Adjusted …
> People List Page & People List Block - Bug Fixes & Edge Case Handling

- css/block/expandable-content.css
- css/ucb-faq-page.css
Standardizes style of Accordion elements. This modifies the style of the `FAQ Page` and `Expandable Content` block in the following ways:
- Adjusts the `FAQ Page` to mirror the Expandable Content's style (blue text, larger type, red hover, + / - icons on toggle instead of a chevron)
- Removes the underlined text-decoration on `Expandable Content`'s title links
Resolves #672
> Standardizes Display of Accordion - style Elements

- css/block/content-row.css
- templates/block/block--content-row.html.twig
Adjusts the following on the `Content Row` blocks:
- On the "Configure Block" modal, switched the order of the tabs so 'Row Content' is on the left and open by default and 'Row Design' is on the right and hidden
- Added three teaser displays: `Large Teaser`, `Large Teaser Alternate`, and `Teaser`. Previously the teaser displays available were Teaser and Teaser Alternate.
- The `Large Teaser` and `Large Teaser Alternate` displays use the focal image wide style images rather than square.
- Adjusts style of the `Teaser` display to mirror other teaser-list style elements, such as the Article List. 
- Adjusted style of the `Tile` style display to more closely mirror the D7 version, which achieved the tile effect with images and text alternating. 
- Fixes bug where internal links, such as …
> Content Row: Block Changes

- css/ucb-menu.css
Closes #722.
Adds CSS changes for the footer menu to only show in the secondary menu when it is a mobile view.
> Mobile Footer Menu Changes

- css/ucb-issue.css
- templates/content/node--ucb-issue.html.twig
- templates/paragraphs/paragraph--ucb-issue-section.html.twig
Fixes the following on Issue Content Types:
- Removes the Secondary Image field from the form and page display. Also removes the hard-coded dark gray box with the title and body in it, as users can use CKEditor5 plugins such as Box, Button, Icons, and Media Library to achieve a variety of left-side layouts. 
- Fixes bug with Teaser view of Categories displaying improperly
- "Read More" capitzalized via CSS instead of hard-coded
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/730
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/107
Resolves https://github.com/CuBoulder/tiamat-theme/issues/704
> Issue Display Changes

- boulder_base.theme
- css/style.css
- css/ucb-newsletter.css
- templates/content/node--newsletter--email-html.html.twig
- templates/content/node--newsletter.html.twig
- templates/field/field--field-ucb-article-categories.html.twig
- templates/field/field--node--field-newsletter-content-blocks--newsletter.html.twig
- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section-content.html.twig
- templates/paragraphs/paragraph--newsletter-section.html.twig
- templates/paragraphs/paragraph--ucb-newsletter-text-block--email-html.html.twig
- templates/paragraphs/paragraph--ucb-newsletter-text-block.html.twig
A rather large update to the Newsletter Node, includes the following:
- Unpublished articles should not display in a Newsletter, and provide a yellow content warning for users in the section they are included in on the web version.
- Newsletter Text Blocks previously had two fixed Text Blocks. This has been updated to a paragraph type with no limit.
- Custom content no longer includes a category field.
- Ability to add Social Media Links to the Footer area. This will use the Social Media Menu links from the site and has a simple on/off checkbox to apply.
- Adds Newsletter type title in header. This is set on the Newsletter Taxonomy.
- 'Feature' thumbnails fixed to a 2:1 aspect ratio
- Section headers fixed to 20px
- Article titles fixed to 18px
- Category links fixed to 10px, and a dark …
> Newsletter: Display Changes + New Features

- js/ucb-latest-issue-block.js
- templates/block/block--ucb-latest-issues-block.html.twig
- templates/paragraphs/paragraph--ucb-issue-section.html.twig
Fixes the following bugs related to the "Issue" content type and associated blocks.
On the Issue Node - fixed visual bug for display on "Teaser" Articles with no thumbnail from displaying a broken `<img>`
- Fixed bug where the "Latest Issue Block" (up to 4 Issues displayed with a button to see more)  would display a "Current Issue block" (one Issue). The template was pointed at the incorrect web component.
- The "Latest Issue Block" adds an "Issue Archive" button below if more than 4 Issues exist on the site. Added conditional rendering to only show if an Issue Archive exists on the site.
Needs a pathauto so the button on the Latest Issues Block works by default (only one expected per site so a similar pathauto to the Class Notes will be implemented)
Includes:
- `tiamat-theme` => …
> Issue Content: Bug Fixes for "Issue" (Node), Latest Issues Block

- css/ucb-issue.css
- templates/content/node--ucb-issue.html.twig
- templates/paragraphs/paragraph--ucb-issue-section.html.twig
-  Fixed a bug where all Articles in a section would link to the first Article in the section
-  Articles that do NOT have a thumbnail or a summary will no longer show the Categories
-  Fixed bug that would sometimes cause images to break display in Title + Thumbnail renders
-  Changed "Feature" style images to take up 100% of the available space and keep an aspect ratio consistent with other Feature images
-  Added spacing between Cover Image and Body, as well as between the Main Menu of the site and the Node Title of "Issue" pages
Resolves #772
> Additional Issue Fixes

- templates/block/block--video-reveal.html.twig
Removed the "A" hard-coded in the render of the text of the video reveal block.
> Removed stray character typo on the video reveal block

- templates/content/node--ucb-article.html.twig
This update:
- Removes margin at the top of articles with header image.
- Moves header image caption to immediately below header image.
- Removes options for black text or hiding the overlay on the header image, setting the white text on dark overlay as the default.
- Updates description of the article header image text field.
Resolves CuBoulder/tiamat-theme#791
Resolves CuBoulder/tiamat-theme#790
Sister PR in: [tiamat-custom-entities](https://github.com/CuBoulder/tiamat-custom-entities/pull/117)
> Updates Articles

- templates/block/block--ucb-form.html.twig
Form block was missing template markup required to allow editing in Layout Builder. This has been corrected.
Resolves #789
> Form Block: Fixes bug preventing editing in Layout Builder

- css/block/events-calendar.css
- templates/block/block--expandable-content.html.twig
This update:
- [Bug] Adds missing `href` attribute to links in Expandable blocks. Resolves CuBoulder/tiamat-theme#853
- [Change] Resets styles targeting `<abbr>` tag in Events Calendar blocks. Resolves CuBoulder/tiamat-theme#837
> Adds two minor style changes

- templates/field/field--field-social-media-email-link.html.twig
It throws a console error despite working just fine. This update removes the error.
Resolves CuBoulder/tiamat-theme#862
> Fixes error thrown by Social Media Icons block email field

- css/ucb-newsletter.css
- templates/content/node--newsletter--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section.html.twig
Adds the optional URL field for Newsletter Section's Custom Content.
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/882
- `custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/131
Resolves #872
> Newsletter: Adds Optional URL to Newsletter Custom Content

- js/ucb-article-slider-block.js
Article Feature: Previously, Articles without thumbnails would still show up in the slider but with a broken image. This has been adjusted so these incomplete Articles are completely omitted from display and only Articles with thumbnails are shown.
Resolves #881
> Articles Slider: Articles without thumbnails are omitted from display

- templates/paragraphs/paragraph--newsletter-section.html.twig
There is a special case for if a Newsletter Section set to "Teaser" display has only one Article or one item of Section Custom Content, then it should span the full width of the web newsletter. This is only the case for a single item in a Newsletter section, odd numbered counts are still 50%. The email version of the Newsletter is unaffected.
Resolves #895
> Newsletter: One Article or One Custom Content in a Section

- css/style.css
Closes #891 . Increases minimum floated image size to 50% on mobile and decreases the text size to 85%.
> Adjust mobile float image size

- css/block/content-row.css
- templates/block/block--content-row.html.twig
- Adjusts DOM order for consistent assistive readability on the `Content Row` display options and reorganizes using pure CSS where applicable
- Adds `role="presentation" and aria-hidden="true"` to links on images so only the title link is read with assistive technologies
Resolves #907
> A11y for Content Rows

- css/block/ucb-collections-block.css
Resolves CuBoulder/tiamat-theme#929 and resolves CuBoulder/tiamat-theme#930.
Adds base font colors for links and text to fix bugs related to background styles.
> Add in base font colors for collection grid

- css/ucb-article-dark.css
Previously, a margin wrapper would apply white top and bottom margins to a dark mode article creating horizontal white bars surrounding content. This has been adjusted so the dark background color spans the entire article.
Resolves #946
> Removes white margins from Dark Mode Article

- css/block/slider.css
Previously the D10 breakpoint for the `Right-Side Content` style `Slider` block would stack the content under the image at a Tablet breakpoint. 
This has been updated to stack under the image at a Mobile-sized breakpoint, while the 75% text size reduction will continue to apply earlier at the Tablet breakpoint to mirror D7.
Resolves #917
> Slider: Right-side Content Breakpoint

- css/block/slider.css
Fixes some overlay issues on smaller screen sizes where the right side overlay wouldn't span the full height and longer strings of text was pushed into non-viewable areas of the slider due to a width setting. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/980
> Slider: "Right-side Content Overlay" styles

- js/ucb-article-list-block.js
- js/ucb-article-list.js
This update:
- [a11y, Remove] Removes unused `sr-only` elements from article list "read more" links. Resolves CuBoulder/tiamat-theme#932
- [Change] Improves the readability of article list JavaScript files (no changes in functionality should be observed).
> Removes unused `sr-only` element from article lists

- templates/webform/webform.html.twig
[a11y, Change] This update adds an `aria-live="polite"` to all webforms. Resolves CuBoulder/tiamat-theme#938
> Overrides Webform template

- css/block/ucb-article-feature-block.css
- css/block/ucb-article-list-block.css
- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
- js/ucb-article-slider-block.js
- Adds edge case to handle Article pages displaying in the "Teaser" style `Article List Block` that may not have an Article body or summary field added, such as an external article reference with no summary added.
- Adjusts to accessibility standards for repeated links on the "Article Grid" and "Article Feature" blocks, all links other than the title have been set to `aria-hidden = "true"`. Images with links set to `role="presentation"` to prevent screen readers from repeating link information two or three times.
- Some JavaScript code formatting, no functionality changes.
- Article Feature: The secondary Articles needed additional margin between the thumbnail and the title/link of the Article
- Article List Block: The entire element had left/right padding preventing alignment with other …
> Article Blocks: A11y fixes, External Article Handling

- templates/block/block--hero-unit.html.twig
Fixes the draggability of the "Hero Unit Block" in Layout Builder. 
Draggability requires `{{attributes}}` to be applied to the outermost container in the Twig template. This change alters the inner containers to use different methods to apply classes and styles rather than also using the `{{attributes.addClass()}}`
Resolves #746
> Hero Unit: Fixes Draggability in Layout Builder

- templates/field/field--field-bs-background-style.html.twig
- templates/field/field--field-bs-content-font-scale.html.twig
- templates/field/field--field-bs-heading-alignment.html.twig
- templates/field/field--field-bs-heading-style.html.twig
- templates/field/field--field-bs-heading.html.twig
- templates/field/field--field-bs-icon-color.html.twig
- templates/field/field--field-bs-icon-position.html.twig
- templates/field/field--field-bs-icon-size.html.twig
- templates/field/field--field-bs-icon.html.twig
- templates/field/field--field-bs-title-font-scale.html.twig
Refactored code to use machine name rather than label value. For grabbing machine name from list fields you need to use `element['#object'].get('FIELD_NAME').value` as machine names aren't in the render array.
These changes affects all the background style field templates. 
Please test each background style option to make sure I didn't mislabel something.
Resolves #1001
> Refactors block style field templates

- js/ucb-collections-block.js
Closes #1006.
Removes filtering by category in the build step of the collection grid.
> Collection item category filtering

- templates/block/block--content-list.html.twig
- Adds `role="presentation" aria-hidden="true"` to image links for an improved screen reader experience
- Removes "Read More" link from `Teaser` and `Full` display
- Hides unpublished content from appearing in Content Lists if user is not authenticated
Resolves #1008
> Content List Block: A11y Changes, Unpublished Content Appearing in Lists

- css/block/content-row.css
- templates/block/block--content-row.html.twig
Adjusts the following styles on the "Content Row" block:
- Aligns image and text to top of the row on these two display types, previously the text was centered
- Feature style display are now fixed to only show 3 items
Resolves #1009
> Content Rows: Styling Adjustments and Feature Fix

- js/ucb-newsletter.js
- templates/content/node--newsletter--email-html.html.twig
- Fixes link color to default `ucb-link` color.
- Programmatically removes `sr-only` text from Category buttons, as Outlook clients ignore css `display:none` unless set on an outermost table so the Categories row would show up as `Categories: [Example 1] [Example 2]...` on Outlook clients. Tested on email with acid.
Resolves #849
> Newsletter: Style Adjustments

- css/block/block-styles.css
- css/block/hero-unit.css
- css/layout-builder-styles.css
- templates/block/block--field-block--node--basic-page--title.html.twig
- templates/field/field--field-bs-background-style.html.twig
- templates/field/field--node--body--basic-page.html.twig
- templates/layout/page.html.twig
Made fixes to layout alignment so that blocks will always be synced.
The main thing is that the left edge and right edge of the row content should align properly. 
There are very slight deviations in the 3 and 4 column options but those are normal for how css handles rows more than 2 columns. (The D7 version has the same discrepancies) 
Test by making tones of rows with different combos of frames and background colors with various different block types
Sister PR: https://github.com/CuBoulder/ucb_bootstrap_layouts/pull/43
Resolves #847
> Block Alignments

- js/ucb-article-feature-block.js
- js/ucb-newsletter.js
- js/ucb-people-list.js
- templates/content/node--basic-page.html.twig
- templates/content/node--collection-item-page.html.twig
- templates/content/node--form-page.html.twig
- templates/content/node--newsletter.html.twig
- templates/content/node--ucb-article-list.html.twig
- templates/content/node--ucb-article.html.twig
- templates/content/node--ucb-class-notes-list-page.html.twig
- templates/content/node--ucb-class-notes.html.twig
- templates/content/node--ucb-faq-page.html.twig
- templates/content/node--ucb-issue-archive.html.twig
- templates/content/node--ucb-issue.html.twig
- templates/content/node--ucb-people-list-page.html.twig
- templates/field/field--field-ucb-article-categories.html.twig
- templates/field/field--field-ucb-article-tags.html.twig
- templates/field/field--field-ucb-person-links.html.twig
- templates/field/field--field_ucb_person_primary_link.html.twig
- templates/includes/ucb-search-box.html.twig
- templates/navigation/menu.html.twig
[Bug, a11y] Resolves CuBoulder/tiamat-theme#1021 Visually hidden (screenreader) elements briefly visible on page load
> Replaces `sr-only` Bootstrap 4 class with `visually-hidden` Bootstrap 5 class

- css/block/expandable-content.css
- `Expandable` legacy shortcode style now mirrors `Expandable Content` Block
- Horizontal inactive tabs on the `Expandable Content` block fixed to inherit color as well.  
Includes:
- `theme` => https://github.com/CuBoulder/tiamat-theme/pull/1034
- `migration_shortcodes` => https://github.com/CuBoulder/ucb_migration_shortcodes/pull/25
Resolves https://github.com/CuBoulder/tiamat-theme/issues/767
> Expandable Color Consistency

- templates/block/block--content-row.html.twig
Omitting the optional image on `Large Teaser - Alternate` style Content Row Blocks does not affect the layout. Previously the missing image would cause the text content to span the full width of available block space, rather than the intended alternating left & right staggered pattern and has been corrected.
Resolves #1048
> Content Row: Missing image maintains layout

- css/ucb-menu.css
Previously there were cases where the child page wouldn't highlight the parent page in menus, specifically when that child page was disabled from the menu. This has been adjusted so that the final parent element in the menu will be highlighted as active as well.
Resolves #1032
> Menus: Parent page highlight in navigation, even if child page isn't enabled in menu

- js/ucb-collections-block.js
Closes #1031.
Removes aggregated categories as it was causing issues when there were more than 50 collection item nodes.
> Remove aggregated categories from Collection grid

- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
Introduced a logic bug in https://github.com/CuBoulder/tiamat-theme/issues/1044 where the various Article Blocks on sites with a large number of Articles could be prevented from rendering the returned JSON:API data, which resulting in what seems like an infinite spinning loader. This has been corrected.
Resolves #1066
> Fixes Article Block Infinite Spin

- css/block/block-styles.css
- css/layout-builder-styles.css
- templates/block/block--article-list-block.html.twig
- templates/block/block--collection-grid.html.twig
- templates/block/block--content-grid.html.twig
- templates/block/block--content-list.html.twig
- templates/block/block--content-row.html.twig
- templates/block/block--content-sequence.html.twig
- templates/block/block--events-calendar.html.twig
- templates/block/block--expandable-content.html.twig
- templates/block/block--hero-unit.html.twig
- templates/block/block--image-gallery.html.twig
- templates/block/block--slider.html.twig
- templates/block/block--social-media-icons.html.twig
- templates/block/block--statuspage-block.html.twig
- templates/block/block--text-block.html.twig
- templates/block/block--ucb-article-feature.html.twig
- templates/block/block--ucb-article-grid.html.twig
- templates/block/block--ucb-article-slider.html.twig
- templates/block/block--ucb-category-cloud.html.twig
- templates/block/block--ucb-current-issue-block.html.twig
- templates/block/block--ucb-latest-issues-block.html.twig
- templates/block/block--ucb-people-list-block.html.twig
- templates/block/block--ucb-slate-form.html.twig
- templates/block/block--ucb-tag-cloud.html.twig
- templates/block/block--video-hero-unit.html.twig
- templates/block/block--video-reveal.html.twig
Updated the block-title class position so that the title class name is getting applied at the right level.
Previously the block-title was wrapping the h2/h3/h4/h5/h6 so that the font-size wasn't getting applied correctly.
Example: The block title is supposed to be 200% of the main font size (16px/1rem). That was getting applied on top of the 160% of h2 instead of h2.block-title just being made 200%. So instead of 32px it was becoming 52px. Essentially we were just double increasing, 16px\*160%\*200% rather than 16x\*200%.
With the change of positioning on the block-title class that resolves this issue. It also fixes an issue with the block-title-increase/decrease options that we didn't know we had.
This also tightens up the vertical spacing a bit with blocks/columns
Resolves #1050
> Heading size fixes

- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
- js/ucb-article-list.js
- js/ucb-article-slider-block.js
- js/ucb-category-cloud.js
- js/ucb-collections-block.js
- js/ucb-current-issue-block.js
- js/ucb-issue-archive.js
- js/ucb-latest-issue-block.js
- js/ucb-people-list-block.js
- js/ucb-people-list.js
- js/ucb-tag-cloud.js
Previously, Pages and Blocks rendering content via JSON:API would use relative pathing, which resulted in content on multi-sites to 404.
This has been corrected on the following:
- People List Page
- Article List page
- Issue Archive
- People List Block
- Current Issue Block
- Latest Issue Block
- Article List Block
- Article Feature
- Article Grid
- Article Slider
- Category Cloud
- Tag Cloud
- Collection Block
Resolves #1080
> Fixes Links on Blocks using JSON:API 

- js/ucb-people-list-block.js
- js/ucb-people-list.js
The `People List Page` and the `People List Block` could run into an API error if there were >50 terms on a site for "Job Type" or "Department", due to how Drupal paginates API results to maintain performance. 
On sites with >50 terms, this would cause a partial render of the page or block, and an error message displaying **"Error retrieving people from the API endpoint. Please try again later."** due to not having the complete list of taxonomies prior to filtering/sorting of the People.
This has been corrected to work with an unlimited number of terms.
Resolves #1065
> People Lists: Corrects API error for >50 taxonomy terms

- templates/block/block--ucb-category-cloud.html.twig
- templates/block/block--ucb-tag-cloud.html.twig
Adds `body` fields to the "Category Cloud" and "Tag Cloud" blocks, previously this was missing from the templates resulting in no body showing up on render even if the user entered one.
Resolves #1090
> Taxonomy clouds: adds missing body field to templates

- css/block/block-styles.css
- templates/block/block--article-list-block.html.twig
- templates/block/block--collection-grid.html.twig
- templates/block/block--content-grid.html.twig
- templates/block/block--content-list.html.twig
- templates/block/block--content-row.html.twig
- templates/block/block--content-sequence.html.twig
- templates/block/block--events-calendar.html.twig
- templates/block/block--expandable-content.html.twig
- templates/block/block--hero-unit.html.twig
- templates/block/block--slider.html.twig
- templates/block/block--social-media-icons.html.twig
- templates/block/block--statuspage-block.html.twig
- templates/block/block--text-block.html.twig
- templates/block/block--ucb-article-feature.html.twig
- templates/block/block--ucb-article-grid.html.twig
- templates/block/block--ucb-article-slider.html.twig
- templates/block/block--ucb-category-cloud.html.twig
- templates/block/block--ucb-current-issue-block.html.twig
- templates/block/block--ucb-latest-issues-block.html.twig
- templates/block/block--ucb-people-list-block.html.twig
- templates/block/block--ucb-slate-form.html.twig
- templates/block/block--ucb-tag-cloud.html.twig
- templates/block/block--video-hero-unit.html.twig
- templates/block/block--video-reveal.html.twig
Moving of the block heading style class to the proper places allows the increase based on options picked (hero/supersize) to work correctly and not become gigantic.
Added in the correct normal/bold options if hero strong or supersize bold is chosen.
By default the hero and supersize should not be bolded.
Resolves #1111
> Block Title Fixes

- css/menu-styles/shadow-styles.css
Closes #1119.
Removes the box shadow from the dark 4 menu style.
> Remove box shadow from Dark 4

- css/ucb-person.css
- templates/field/field--field-ucb-person-email.html.twig
Closes #1130. 
Adds an overflow-wrap to the email address in the person page in order to stop the email from overflowing into the content.
> Add overflow-wrap to email and links

- boulder_base.info.yml
- css/block/hero-unit.css
- css/style.css
- templates/layout/page.html.twig
Closes #1126.
This adds the intro wide region to the block layout. This will primarily be used by images and hero units for a top banner.
> Intro Wide region implementation

- templates/block/block--site-info.html.twig
- templates/regions/region--site-information.html.twig
This update:
- [Bug] Corrects the site link in the site contact info footer block to correctly point to the active site's home page. Resolves CuBoulder/tiamat-theme#1127
- [Change] Changes the privacy policy link to link directly to the privacy policy. Resolves CuBoulder/tiamat-theme#1093
> Updates site footer links

- templates/block/block--ucb-article-feature.html.twig
Fixes a template issue preventing the 'Read More' link from linking to the chosen url correctly. 
Resolves #1163
> Article Feature: fixes 'Read More' link

- boulder_base.theme
Closes #1081.
Changes the favicon path to be relative to the site path.
> Favicon path change

- js/ucb-people-list-block.js
- js/ucb-people-list.js
Previously in the case where you had a `People List Page` or `People List Block` and then removed an Image from the Media Library that was used as a thumbnail for a `Person` page, this would make that respective Person Page's thumbnail ID to become `'missing'` rather than a `null` value, which would cause the Person List Page to completely break unless that Person's thumbnail image is fixed.
This has been corrected with additional checks in these rare cases. It will also use the Default Avatar in specific displays such as the Grid. 
Resolves #1175
> People Lists: Removing an Image breaks Lists

- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
- js/ucb-article-slider-block.js
Previously Article Aggregator Blocks (includes `Article List`, `Article Feature`, `Article Grid`, `Article Slider`) could sometimes display `Articles` out of chronological order. This issue was due to the asynchronous nature of the chained API calls, which could cause Articles that required additional processing (e.g., generating a summary from the article body) to be placed out of order after processing completed while other more field complete (but potentially chronologically earlier)  Articles "finished" before them.
Now, all Articles are processed and appended to the page in their original order, ensuring the chronological display of articles across all Article aggregator page/blocks
Resolves #1184
> Article List blocks: Chronological Order

- boulder_base.libraries.yml
- css/block/block-styles.css
The heading styles `Hero` and `Hero Bold` have been adjusted to both use 'Roboto Condensed', mirroring the D7 block style versions
Resolves #1164
> Block styles: Heading Style 'Hero' Font Family Changes

- css/ucb-article-dark.css
- css/ucb-article.css
Corrects the following on Articles with an `Article Title Background` set
- On mobile sizes, the navbar hamburger menu could become unclickable due to an Articles Title Background overlay extending too far.
- Removes extra padding on "Dark mode" Articles with an Article Title Background image set that created an extra gap between the navbar and the image
Resolves #1187 
Resolves #1195
> Article: Article Title Background Style Adjustments

- css/style.css
Adds a 'Margin Clear' style for headers and paragraphs
Includes:
-`tiamat-profile` => https://github.com/CuBoulder/tiamat10-profile/pull/182
-`tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/1201
Resolves https://github.com/CuBoulder/tiamat10-profile/issues/152
> CK5: Margin Clear styles

- css/block/content-list.css
- templates/block/block--content-list.html.twig
Updates the look of the 'Sidebar' style of `Content List` Blocks to better match D7, as specified by Kevin in the ticket. Will swap the image to the left and make smaller on both desktop and mobile sizing.
Resolves #1169
> Content List Block: Updates to 'Sidebar' Style

- css/layout-builder-styles.css
- templates/layout/page.html.twig
Fixed sidebar spacing so that things vertically aligned. 
Also solves the problem of a mobile horizontal scroll bar appearing because of the `g-0` class. 
Changed the column sizes to match the same sizes as layout builder sidebars. 
Finally fixed alignment of multi-column layoutbuilders + a sidebar. Though this should be a rare case, the new changes make it so all the content aligns as expected.
To test the horizontal mobile scroll bar fix you'll need to have a block or menu in the block layout sidebar.
Resolves #1198
> Sidebar spacing fixes

- boulder_base.info.yml
- boulder_base.libraries.yml
- css/colorbox-image.css
- templates/media/media--image--colorbox-small-square.html.twig
- templates/media/media--image--colorbox-small-thumbnail.html.twig
- templates/media/media--image--colorbox-small.html.twig
- templates/media/media--image--colorbox-square.html.twig
Adds 4 new colorbox image styles: `Colorbox Small` , `Colorbox Small Square`, `Colorbox Small Thumbnail`, `Colorbox Square`. On click, these open up a modal with the full image and caption.
Includes:
- `tiamat-theme` => https://github.com/CuBoulder/tiamat-theme/pull/1205
- `tiamat-custom-entities` => https://github.com/CuBoulder/tiamat-custom-entities/pull/160
- `tiamat-profile` => https://github.com/CuBoulder/tiamat10-profile/pull/185
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1174
> New Image Styles: Colorbox Image Styles

- js/ucb-article-list.js
Fixes a bug with the `Article List` introduced when we refactored Article Lists to strictly enforce chronological order despite API timings. The bug would cause exclusions to throw an API Error instead of skipping processing entirely, which they had done when chronological order was not strictly enforced. 
This has been corrected and Articles flagged with Excluded Categories / Excluded Tags are properly removed with an additional check.
Resolves #1207
> Article List: Fixes Exclusion Filters

- css/style.css
Removes admin toolbars/alerts from displaying when previewing a page using the Responsive Preview tool for site editors to preview a mobile or tablet display
Resolves #1218
> Responsive Preview: Removes admin toolbars/alerts from displaying on Responsive Preview for site editiors

- templates/content/node--ucb-person.html.twig
Fixes a display issue where a Person Page would arrange back to 2 columns on a mobile display instead of 1.
Resolves #1215
> Person page: fix mobile columns

- js/ucb-article-list-block.js
Removes the Thumbnail requirement for `Article List Blocks`, which would previously filter out any Articles that do not have a thumbnail field from showing up across all displays. This change will make the block perform more like the `Article List Page` and not omit Articles missing those fields from being displayed on the final output.
Resolves #1224
> Article List Block: remove image requirement for all displays

- css/block/content-list.css
Adjusts size of "Sidebar" - styled Content List Block images to be exactly 75px on desktop and 50px on mobile screen sizes. Previously there was additional width added.
Resolves #1217
> Content List: Image size adjustment

- css/style.css
- css/ucb-menu.css
Closes #1197.
Makes the secondary and mobile footer menu to stay within a column for the mobile menu. This also disables the footer menu being able to expand in the mobile menu.
> Secondary and Mobile Menu fixes

- css/ucb-accordion-styles.css
A CSS specificity bug existed in the expandable content block set to horizontal or vertical tab display. The bug caused accordions created using the CKEditor 5 Bootstrap Accordion plugin and nested within the content area to be unexpectedly hidden. This update resolves the issue.
Resolves CuBoulder/tiamat-theme#1228
> Fixes CSS bug causing accordions nested inside tabbed expandable blocks to be hidden

- templates/block/block--expandable-content.html.twig
- templates/block/block--image-gallery.html.twig
- templates/block/block--slider.html.twig
- templates/block/block--video-hero-unit.html.twig
- templates/block/block--video-reveal.html.twig
Replacing our ID generation for these blocks so that reusable blocks don't run into errors with duplicate reusable blocks on the same page.
This affects the video reveal, slider, image gallery video hero unit, and expandable content blocks.
Closes #1245 
Closes #1137
> ID generation replace

- templates/block/block--slider.html.twig
- templates/paragraphs/paragraph--slider-image.html.twig
Added three new image styles:
Slider Ultrawide (1600x600)
Slider Widescreen (1600:900)
Slider 3:2 (1500:1000)
Each style has the proper sizing dictated by Kevin
The Slider block has been updated to have the proper names and sizes associated with them.
The slide paragraph now has the default image style set to Original.
The slider block template has had it's sizing logic moved to the paragraph slide template.
The paragraph slide template uses parent logic to check what side the slider is going to be and applies the appropriate style to each image.
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/165
Closes #1240
> Update Slide Size/Image

- js/ucb-article-slider-block.js
- templates/block/block--ucb-article-slider.html.twig
While a rare situation, if a user happens to add two copies of a re-useable `Article Slider` block to the same page, it would cause them both to break. Similar to the other JavaScript blocks, this issue has been corrected by giving every instance of the block a Unique ID. 
Resolves #1247
> Article Slider: Fixes Issue with Multiple Reuseable Article Slider Blocks on the same Page

- templates/block/block--content-list.html.twig
Resolves #1251.
Adds the ability to add collection item pages to the content list.
Custom Entities -> https://github.com/CuBoulder/tiamat-custom-entities/pull/168
> Content list changes

- css/block/ucb-mega-menu.css
Resolves #1238.
Adds css to make images span the width of the text-above div, and changes the columns to be reduced to one in tablet width.
> Mega Menu Tablet changes

- css/ucb-menu.css
- js/ucb-menu.js
Closes #1231.
Solves the problem of a split mobile menu by combining the various mobile menus into one. This should resolve the bug in all situations.
> Mobile Menu

- templates/layout/page.html.twig
Resolves #1212.
Adds a conditional to the mobile menu toggle to only appear when there is a menu on the page.
> Mobile Menu: Adds conditional to toggle

- css/ucb-print.css
Resolves #1276.
Adds css to force the hero and video reveal to have black text at all times.
> Print css to force black text

- css/menu-styles/simple-styles.css
Resolves #1282.
Corrects the Dark 3 menu style to have the secondary menu links be in line when the secondary menu is above.
> Dark 3 Secondary Menu CSS change

- css/block/video-reveal.css
- js/ucb-video-reveal.js
- templates/block/block--video-reveal.html.twig
Resolves #1204 and #1286.
Changes the video reveal to have the image as a background images and limits the height to 160px larger than the text content.
> Video Reveal height solution

- css/menu-styles/highlight-styles.css
- css/menu-styles/ivory-styles.css
- css/menu-styles/layers-styles.css
- css/menu-styles/minimal-styles.css
- css/menu-styles/shadow-styles.css
- css/menu-styles/swatch-styles.css
- css/menu-styles/tradition-styles.css
- css/ucb-secondary-menu-region.css
Resolves #1285.
Changes the functionality for the buttons to only show when it is the active link. This change eliminates social media buttons and adds the functionality of the no button css to non-active links.
> Secondary Menu Button functionality change

- templates/content/node--newsletter--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section.html.twig
- Centering on Newsletter pages (the page, not the email version)  was not working correctly for user-created content in Teaser, only if an image was not supplied. This has been corrected. Resolves https://github.com/CuBoulder/tiamat-theme/issues/1264
- Articles added to newsletters were showing `&nbsp;`  as plain text in strange places that do not appear in the original articles. This has been corrected - this would happen with Articles where no summary field is provided. The `&nbsp` was caused by how we handle generating a summary to put in place of that missing field in Twig specifically and has been adjusted
- Newsletters are limited to 600 px wide in the preview window but when sent through Marketing Cloud and opened in Windows Outlook, and always were the full width of the window, …
> Newsletter: Major bug fixes and style adjustments

- templates/content/node--ucb-person.html.twig
[bug] Resolves CuBoulder/tiamat-theme#1304
> Separates person first and last name with space instead of newline

- boulder_base.theme
- css/ucb-article.css
- templates/content/node--ucb-article.html.twig
Removed div displayed image and set it as a background image. Set the background image to use the `section_background` image style to avoid large image files.
Set background positioning using new preprocess in .theme Preprocess works like it does in the layout builder sections except it will update immediately if the file image's focal point is updated.
Updated css to reflect new changes. Removal of `absolute` positioning fixes the problem with the navigation being covered by the title. Everything should scale well now.
Changed the top padding to be 300px vs 200px to imitate the old version's bigger title image.
Resolves #1292
> Article Title Background Update

- templates/field/field--node--body--basic-page.html.twig
The basic page body block wasn't being rendered at the right level. This caused it not to be editable or removable at the layout builder level. If multiple body sections were added they couldn't be deleted and a "body" title was added to each new addition.
Closes #1280
> body template move

- css/block/ucb-mega-menu.css
- css/ucb-sticky-menu.css
- js/ucb-mega-menu.js
Resolves #1317 and #1316.
Removes mega menus from the sticky menu and converts them into normal links. It also adds base default colors for links in mega menus to account for site settings.
> Remove Mega menu from Sticky menus and add default link color

- css/style.css
Add proper alignment on floated images.
Should only affect images with large amounts of caption text.
Resolves #1314 
Resolves #1249
> Fix for alignment of floated images with long captions

- css/style.css
Previously the required field indicator (red asterisk) was missing from Forms added as a `Webform block` (not to be confused with Form blocks).  This has been corrected so they are visible.
Resolves #1321
> Webform Block: Adds Required field indicator

- js/ucb-people-list.js
Previously if you had a People List Page with `Group by` set to Department or Job Type, and had filter on that term, you could possibly see groupings of people for terms not selected in the filter, if the Person pages had multiple terms.
For example: on [https://www.colorado.edu/alc/our-people/undergraduate-advising](https://www.colorado.edu/alc/our-people/undergraduate-advising), the Faculty group should not show up as it is a term applied to every Person Page, but NOT included in the filters.
This has been corrected so only the filtered groups in the `Includes` for that term show up as a Group.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1259
> People List Page: Selecting 'Group by Job Type or Department' with Filters applied to that term, only shows allowed groupings

- templates/content/node--ucb-person.html.twig
- templates/field/field--field-ucb-person-first-name.html.twig
- templates/field/field--field-ucb-person-last-name.html.twig
[bug] An issue existed where a space was trimmed between the first name and last name on person pages due to the names being separated by a newline. This update resolves the issue. Resolves CuBoulder/tiamat-theme#1304
> Places first name and last name on the same line to prevent trimming of the space between them

- js/ucb-menu.js
Resolves #1290.
Adds a secondary check in the case where the menus exist but there are no menu links within them.
> Hide hamburger menu when there are no menus

- boulder_base.theme
[bug, severity:moderate] An issue existed where a site would crash if it contained a custom logo. This was due to the use of a [deprecated function call removed in newer versions of Drupal](https://www.drupal.org/node/2940031). This update resolves the issue by replacing the deprecated function call with the correct call. Resolves CuBoulder/tiamat-theme#1342
> Replaces deprecated function call on sites with a custom logo image

- js/ucb-person-article-list.js
In cases where a Person has over 10 Articles with their linked byline term set on the Articles, the logic on the Articles by Person block could cause an infinite spinning loader due to logic in how the block should handle pagination. This has been corrected to match the other Article aggregator build processes. 
Resolves #1332
> Articles by Person Block: Fixes Infinite Spinning Load on Person Page

- css/block/slider.css
- templates/paragraphs/paragraph--slider-image.html.twig
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1356
> Fixes Slider block link color and special character rendering

- js/ucb-people-list-block.js
- js/ucb-people-list.js
[change] Previously, job type sorting on people lists was limited to alphabetical by job type name. This update changes job type sorting to respect the order for job types shown on the job type taxonomy page. Resolves CuBoulder/tiamat-theme#1368
> Sorts by job type weight instead of alphabetical in people lists

- templates/field/field--field_mega_menu_links_desc.html.twig
Resolves #1372.
Removes the render and strip tags from the mega menu link description
> Remove striptags render from mega menu desc

- js/ucb-related-articles.js
- templates/content/node--ucb-article.html.twig
> Related Articles: Fix base path

- css/ucb-menu.css
- templates/layout/page.html.twig
- templates/regions/region--secondary-menu.html.twig
Resolves #1336.
Adds the ability to use footer menus while using no other menus and have them show up in the mobile menu.
> Only footer menu in the mobile menu fix.

- css/style.css
- templates/media/media--image--colorbox-small-square.html.twig
- templates/media/media--image--colorbox-small-thumbnail.html.twig
- templates/media/media--image--colorbox-small.html.twig
- templates/media/media--image--colorbox-square.html.twig
These changes affect `Colorbox Small - Square`, `Colorbox Small - Thumbnail`, `Colorbox Square`, and `Colorbox Small` image styles.
1. Previously the 4 Colorbox image styles would only use a caption for the lower description of the click to zoom functionality  that appears when zoomed. We have enabled a fallback such that if no caption is added, it will use the alt tag of the image. If no alt tag exists either, it will be blank. Resolves #1393 
2. The Colorbox Image float left and float right were not being applied due to these being 'snowflake' images using a different template to enable the click to zoom functionality. This has been corrected and should float left or right as expected. Resolves #1379
> Colorbox Image Styles: Allows 'alt' tag fallback for Caption, Fixes Floats

- css/block/ucb-latest-issue-block.css
- css/ucb-article.css
- css/ucb-issue.css
- templates/content/node--ucb-article.html.twig
The tag showing that an Article appears in an Issue (below Categories and Tags) on Article pages previously had the icon appearing differently than the Category and Tag icons due to missing CSS. This has been corrected. (You will need to link an existing Issue to an Article to test via the 'Link To Issue' tab)
Previously, images placed in the footer (or anywhere else for that matter) on an Issue page were showing up at 100% sizing due to not specific enough CSS being applied to all images. This has been corrected.
We have resized the images of Issue covers that appear in the `Latest Issue` block to a larger size, mirroring the D7 version where each card takes up 25% of the horizontal container.
Resolves #1382 
Resolves #1383 
Resolves #1384
> Issue Fixes: "Link to Issue" on Articles tag style, Issue page images, Latest Issues Block

- templates/paragraphs/paragraph--newsletter-section.html.twig
- Corrects an issue where a certain number of `Teaser` sections and content items with images could cause the section to "break out" of the parent container and get displayed pinned to the left, due to an error in the html template that would close the section too early if specific conditions were met.
- If there is only one content item in a Teaser section, it will take up 100% of the space. Otherwise they will fall side by side taking up 50% of the space. This not working was also partially attributed to the above error.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1354
> Newsletter (Web Version): Fixes desktop version display

- css/ucb-article-list.css
- js/ucb-article-list.js
- Adds a Reset button to the user-accessible filters for Category and Tag on an Article List Page that will reset the component to the initial state
- Fixes a bug that could present when clicking Apply Filters with 'All Category' and 'All Tags' selected that could bring in additional outside Terms from what the component initialized with and originally filtered on. This seemed to happen if you clicked Apply Filters right as the component loaded, but has been corrected.
- Adds an error message for `No Results Found` if the provider returns any number of Articles with filters applied, but all those results get filtered out in the exclusion process. Previously there was not a case built for this with the new filters and a user could be presented with a blank component.
Resolves …
> Article List Page: Adds Reset button to Exposed Article List Filters and Minor Bug/QoL Fixes

- css/ucb-accordion-styles.css
Fixes visual issue where inserting a Column into an Accordion would cause a horizontal scrollbar to appear within the Accordion body. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1421
> Accordions: Fixes Accordions containing Columns Overflow

- css/style.css
- Adds spacing surrounding left and right aligned video media and the text.
- On mobile screens-- left, right, and center alignments are removed and the video spans the full-width of the content. This prevents videos from becoming too small when floated and adjusts the Center-aligned videos to mirror the full-width look instead of maintaining pillarboxed 'centered' spacing on mobile.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1433
> Video Media: Fix floated video spacing, remove alignments on mobile screens

- css/block/ucb-article-grid-block.css
- js/ucb-article-grid-block.js
Replaces the Article Grid Block's list of Article thumbnails with the `focal_image_wide` image style, which eliminates the need for applied CSS styles on the thumbnail verion, which was not consistent across browsers.
Previously the block was using a CSS styled version of the `focal_image_square` because our `UCB Focal Image Enable` module, which enables access to our variety of image styles via API, did not yet have access to the wide image style at the time of the Article Grid block's development. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1403
> Article Grid: Replaces styled square thumbnail image with wide image

- templates/content/node--ucb-person.html.twig
Adds an on / off toggle to make the Articles by Person block on a Person page optional.
Includes:
- theme => https://github.com/CuBoulder/tiamat-theme/pull/1437
- custom_entities => https://github.com/CuBoulder/tiamat-custom-entities/pull/186
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1398
> Articles by Person: On/off toggle

- css/ucb-form-page.css
- templates/block/block--ucb-form.html.twig
Fixes issue where webform blocks placed in Sections with column width 50/50 or 33/66 were too narrow. This was due to styles applied so the form would not span the full width on a single column container. 
Adjusted so that one column layout will continue to span the 66% of the container but smaller multi-column layouts span the entire width.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1440
> Webform: Adjusts max width at different column widths

- js/ucb-latest-issue-block.js
Prevents an error in the Latest Issue Block where it would fail to fetch due to a missing subpath. This has been corrected. 
Resolves #1462
> Latest Issue Block: fix missing site subpath

- templates/content/node--ucb-article.html.twig
This update:
- Removes instance of `render|striptags|trim` from article title image caption template.
[bug, severity:minor] Resolves CuBoulder/tiamat-theme#1459
> Resolves special characters not rendering correctly in article title image captions

- templates/content/node--newsletter--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section.html.twig
- Header issues fixed including: Campus logo too small, Website link wrong color, Newsletter title too small, and date and website link should be smaller. Email header too large. Provided correct email header from Lissa ( thanks!).   **NOTE**: Link color SHOULD have all the correct client-specific and dark/light mode overrides being applied to force brand colors... but is not guaranteed to work across all clients equally due to email HTML having zero standards between clients. 
- Fixes spacing  between border and next articles in a series of Articles or User-content. Previously the top spacing was too small.
- Fixes a footer issue where sometimes the background wouldn't apply and there would present white text on a white background. 
- Fixes header images cropping oddly
Resolves …
> Newsletter: Additional Style Fixes

- boulder_base.theme
- config/install/boulder_base.settings.yml
- css/layout-builder-styles.css
- css/ucb-brand-bar.css
- templates/layout/page.html.twig
- templates/regions/region--site-information.html.twig
Handful of updates for the above and below content regions as well as the homepage footer style
Sister PR: https://github.com/CuBoulder/ucb_site_configuration/pull/71
Resolves #1435
> Homepage updates

- js/ucb-related-articles.js
Previously the Related Articles block would use the Article link provided by the JSON API response unmodified, which was relative and missing the subpath. This would lead to broken URLs on sites with subpaths. This has been corrected.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1464
> Related Articles: fix relative path response

- templates/layout/page--search.html.twig
- templates/layout/page.html.twig
Previously, some regions were missing from search pages, such as the sidebar regions. This update adds those regions to search pages to match our other pages, allowing blocks to be placed in the sidebar using block layout. This fix is needed ASAP for the homepage site.
[bug] Resolves CuBoulder/tiamat-theme#1453
> Adds missing regions to search pages

- templates/block/block--video-hero-unit.html.twig
- templates/field/field--block-content--field-hero-bottom-padding.html.twig
- templates/field/field--block-content--field-hero-top-padding.html.twig
Adding content padding for the video hero unit to extend height more easily for users. 
Overrides css with inline style.
Options were added in the Design tab
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/193
Resolves #1477
> Video Hero Unit Content Padding

- css/block/ucb-mega-menu.css
Resolves #1468
Adds padding to the mega menu columns to prevent content overlap.
> Padding for mega menu columns

- templates/regions/region--site-information.html.twig
Removal of the `ucb-home-link` as the `{{ content }}` generates that link properly for the homepage.
This also means we do not hide the Site Contact Info Footer in the Block Layout. The homepage is currently configured this way so that's no worry there. When they add social media links they'll just need to make sure that it is the first item in the Site Information region to stack properly.
Updated various links to the new ones provided by Wendy
Resolves #1493
> Update Homepage Footer

- css/block/ucb-article-feature-block.css
Previously Article Feature Blocks with the Image Size set to `Wide (slider image style)` would come through as 3:2 aspect ratio rather than 16:9, which is used for the slider. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1501
> Article Feature: Fixes aspect ratio for Wide images

- templates/content/node--newsletter--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
- Removed the hard-coded "View on Website" link. This will link correctly to the Newsletter page it is generated from. The hard-coded link was due to a completely re-written header and was left in unintentionally from development.  
- Added stricter styling rules to force iOS devices to show images at the proper width. Previously they would all take on the same width on iPhones only. 
- The blue link color should now be consistent across the Newsletter, along with removing the underline link decoration. 
- Missing images should be fixed for complex site urls, but will need to be tested in production. 
- Adjusts spacing on the top of the newsletter. Previously there could be a large gap in between the header and the content if you intentionally left out fields such as the Intro Image or …
> Newsletters: Bug Fixes, Layout Adjustments

- templates/block/block--content-row.html.twig
Updated content rows so that teasers are using the correct image style with the right 2:1 ratio.
A new image style was created to support this update. 
There was also a bug with the code in which the large teasers would display as squares if the rows were unlinked. That has been updated to show correctly as wide.
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/196
Resolves #1503
> Modify Image Styles in Content Rows

- js/ucb-class-notes-list.js
Previously the Class Notes List page would strip out WYSIWYG HTML from the aggregate display. This has been adjusted so that images, links, etc added to a Class Note page via WYSIWYG editor are allowed to display while malicious input is not. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1523
> Class Notes List: Allow WYSIWYG Class Notes to display correctly

- css/ucb-site-contact-info-footer.css
Resolves #1525.
Removes wrapping from the site info contact footer to remove the extra space.
> Remove wrap from info footer

- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
Previously the Email HTML of Newsletters would not display unpublished Articles. Now they will display so site-editors can verify and proof content before mailing. There is a content warning on the Node of any Articles that are unpublished. 
Note: Articles must still be manually published before sending the email, or could result in email recipients getting broken links. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1517
> Newsletters: allow unpublished to show in Email HTML preview

- css/block/ucb-mega-menu.css
Resolves #1530.
Forces the color of links in the mega menu to be blue to resolve issues of links not showing up.
> Mega menu Link color changes

- js/ucb-article-list.js
This update adds the Article Syndication "read more" article list, for use with the Campus News block. The article list is automatically created on sites using the CU Boulder Article Syndication module (if it doesn't already exist) and aliased to `/syndicate`. It allows URL parameters to specify category, audience, and unit filters.
[new] CuBoulder/ucb_article_syndication#3
Sister PR in: [ucb_article_syndication](https://github.com/CuBoulder/ucb_article_syndication/pull/6)
> Adds Article Syndication "read more" article list

- css/ucb-related-articles.css
- js/ucb-related-articles.js
- templates/content/node--ucb-article.html.twig
Previously the Related Articles block could produce results that were older than expected while more recent related Articles could be missing. The block has been completely reworked to use a modern Web Component style of the other Article List blocks we've developed as well as produce better and more recent Article matches by picking through a pool of the most 50 semi-related to find the top 3.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1526
> Related Articles: Refactors block for better relatedness scoring, faster generation

- js/ucb-expandable-content.js
- templates/navigation/menu--extras.html.twig
Resolves #1536.
Changes the functionality of the hash set function to only affect menus that are not mega menus.
> Resolve URL Hash for mega menus

- boulder_base.libraries.yml
- css/menu-styles/ucb-sidebar-gray-styles.css
- templates/layout/page.html.twig
Styles applied when the light gray sidebar menu style option is picked in the theme configuration. Styles override basic options with new css file.
Sister PR: https://github.com/CuBoulder/ucb_site_configuration/pull/75
Resolves Issue #1513
> Sidebar menu theme styles

- js/ucb-related-articles.js
Fixes an issue with v2 of the Related Articles block where it could include itself in Related display.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1549
> Related Articles: Will Not Include Self

- js/ucb-newsletter-list-block.js
Previously the Newsletter List Block would just use the path returned via the API, which presented an issue on multisite. This has been corrected
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1556
> Newsletter List Block: fixes pathing of linked Newsletters

- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
We changed how Newsletter Article images are referenced for better generation on multi-site domains in particular. With this change the primary (www.colorado.edu) domain was dropped. This has been re-added. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1561
> Newsletter: Re-add domain to Article Thumbnails (Wide and Teaser) referenced in a Newsletter

- css/block/ucb-mega-menu.css
CU Buttons placed in a Mega Menu could have their text color overwritten to the default link blue due to overly aggressive css rules. This has been corrected so menu links retain their intended colors and Buttons receive their expected styles
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1562
> #1562 - Mega Menu: fix Button color being over-written

- templates/field/field--block-content--field-calendar-code.html.twig
Previously the Events Calendar block would only allow the "List" type Widget as configured by `https://calendar.colorado.edu/help/widget` and would not correctly display the "Mini Calendar + List" widget option -- which adds an interactive mini calendar to the Events Calendar block. 
This has been corrected so both 'Widget Types' will work with the block.
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1567
> #1567 Events Calendar: Allow Mini Calendar + List option

- js/ucb-people-list-block.js
- js/ucb-people-list.js
- On the People List Page and People List Block, previously Person pages with a short body field would not show that in these aggregator displays due to a logic bug which would only trigger if the Person page returned had to generate a summary, in cases where the body was too long. This would lead to short Person page body fields not displaying. This bug has been corrected. Resolves https://github.com/CuBoulder/tiamat-theme/issues/1572
- Previously on the People List Page  if the People were sorted by Last Name but some People shared a Last Name, it would display them in order of creation. This has been corrected so that it will sort by Last Name, and then First Name in cases of shared last names. Resolves https://github.com/CuBoulder/tiamat-theme/issues/1573
> People Lists: Fix short body fields not displaying. Refines Alphabetical sorting of lists

- css/block/block-styles.css
- js/faculty-publications.js
- js/ucb-article-feature-block.js
- js/ucb-article-grid-block.js
- js/ucb-article-list-block.js
- js/ucb-article-list.js
- js/ucb-article-slider-block.js
- js/ucb-category-cloud.js
- js/ucb-current-issue-block.js
- js/ucb-latest-issue-block.js
- js/ucb-newsletter-list-block.js
- js/ucb-people-list-block.js
- js/ucb-people-list.js
- js/ucb-tag-cloud.js
- templates/block/block--article-list-block.html.twig
- templates/block/block--faculty-publications.html.twig
- templates/block/block--ucb-article-feature.html.twig
- templates/block/block--ucb-article-grid.html.twig
- templates/block/block--ucb-article-slider.html.twig
- templates/block/block--ucb-category-cloud.html.twig
- templates/block/block--ucb-current-issue-block.html.twig
- templates/block/block--ucb-latest-issues-block.html.twig
- templates/block/block--ucb-newsletter-list-block.html.twig
- templates/block/block--ucb-people-list-block.html.twig
- templates/block/block--ucb-tag-cloud.html.twig
- templates/content/node--ucb-article-list.html.twig
- templates/content/node--ucb-people-list-page.html.twig
- templates/field/field--block-content--field-calendar-code.html.twig
Previously Aggregator/ API-driven content would show various Error messaging to reflect Content-Aggregator blocks failure to display results, such as No Results found, API errors, overly aggressive filtering, etc. intended to prompt site-editors to take action and intervene to fix the content to display properly. These errors would show indiscriminately of a user's role. 
This has been adjusted so Anonymous users don't see the Error messaging and only show it to Authenticated users. This includes pages such as the Article List Page, the People List Page as well as blocks such as Article aggregator blocks, People List block, taxonomy clouds, and more. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1392
> Aggregators will only display error messages to Authenticated Users

- js/ucb-newsletter.js
- templates/content/node--newsletter--email-html.html.twig
Previously images placed in the Newsletter Blocks `Newsletter Block Text` section would show up in the Email HTML with relative pathing and no fixed style sizes, resulting in very broken images. This has been corrected so images should render at full-width of their section at both options -- one Block at full width OR multiple Blocks side by side. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1605
> Newsletter: Fixes pathing and size of images within Newsletter Content Blocks 

- templates/content/node--newsletter--email-html.html.twig
- templates/paragraphs/paragraph--newsletter-section--email-html.html.twig
Due to how Microsoft Outlook on Windows 10/11 uses a custom render engine based on Microsoft Word instead of anything standardized, the `Dark-Box` style of email was hard to read and would come through with missing backgrounds. This has been adjusted to conditionally render wrapping elements to help try to enforce background.
Resolves #1608
> Newsletter: Dark Boxed email's Article sections in Outlook on PC have no background

- css/ucb-brand-bar.css
Previously on www.colorado.edu,  the Search Icon could dissapear on small screen sizes. This has been corrected. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1618
> #1618 - Fixes missing Search Icon on Mobile size screens

- boulder_base.libraries.yml
- css/block/hero-slider.css
- js/block/hero-slider.js
- templates/block/block--ucb-hero-slider.html.twig
- templates/field/field--paragraph--field-hero-slide-image-text.html.twig
- templates/paragraphs/paragraph--hero-slider-image.html.twig
Update the paragraph to not striptags and trim. Rather we create a new template for the field so that special characters aren't broken on render.
Add `data-bs-wrap="false"` to stop the looping of the slider
Replaced fixed 100vh height with responsive aspect-ratio (16/9 desktop, 4/3 tablet, 3/4 mobile). Set max-height: 100vh, used relative positioning, and ensured images scale properly with object-fit: cover.
Added restart and pause/play buttons
Add unstyled class so extra padding is removed.
Sister PR: https://github.com/CuBoulder/tiamat-custom-entities/pull/207
Resolves #1625
> Hero Slider Updates

- js/ucb-newsletter.js
Previously the helper functionality to try to mitigate broken image src paths due to relative links in WYSIWYG fields could cause sites like `colorado.edu/<sub>/<addtl-sub>` to duplicate pathing information in the transition into absolute paths, leading to broken absolute links and images. This functionality has been adjusted and refined. 
Resolves https://github.com/CuBoulder/tiamat-theme/issues/1626
> Newsletter: Adjust Relative to Absolute pathing of WYSIWYG Images

- js/ucb-people-list-block.js
- js/ucb-people-list.js
Previously on the `Person Page` form, linking to an internal page or node for a Person's Primary Link could result in broken links depending on how the linked page was referenced -- either by internal url or entity node ID. Drupal would store this link either as `internal:/` or `entity:node:/`, depending on how it was input (such as`/home` versus `Home (1)` selected via autocomplete) and they would each be returned differently to the aggregators content types.
The `People List page` and `People List block` only correctly handled one of these two ways in the final render, but this has been corrected to handle both.
Resolves #1631
> People Lists: Fix linking of internal pages

- templates/navigation/menu--extras.html.twig
- templates/navigation/menu.html.twig
Previously adding special characters like apostrophes, ampersands, etc. to a Mega Menu item or disabling the page so the 'Hidden' icon would show for site editors could prevent the Mega Menu from functioning properly -- leading to WSOD errors or JavaScript errors. 
The logic for assembling these menus has been adjusted to handle these cases
Resolves #1649
> #1649 - Resolves Mega Menu cases for special characters and hidden icons
